### ISSUE TITLE
Music "forgets" that it has already scanned successfully, when music folder unshared from group

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#581] opened 2017-09-20 11:11 UTC
Let a scan run via ./occ, album and music files appear in the app when finished.
Logged off and logged on a day later, the music app has "forgotten the successful scan, no albums or files shown, a message is presented to scan again...
The mount containing the music files is on smb granted to my user and additionally to a group. What I did was to remove the group (not me). The group did not contain myself as additional user, so no double removal possible.

**Comment by paulijar** [comment] 2017-09-20 11:49
When a music file/folder is unshared from a group, the unshared files are currently removed from everyone's music libraries and those users still having access to the files need to rescan. This behavior is sub-optimal, but it would be quite complicated to do it right and remove the tracks from only those users who no longer have access to them. This is probably still doable, but so far I have not seen it to be worth the effort. Anyway, the issue is valid and maybe some day I'll find time to fix it.

**Comment by mmattel** [comment] 2017-09-20 12:08
Just to clarify:
user: A, B C, D
group named HELLO
HELLO group members: B, C, D
Music files mount grants access to user A and group HELLO
Scanning music for user A only
Removing group HELLO from the mount
Music app forgets sucessful scan for user A (which was not touched)
The only relationship between user A and group HELLO is the mount

**Comment by paulijar** [comment] 2017-09-20 13:02
Yes, that's how it works. Unsharing a file from a group is currently handled by removing that file from everyone, including the owner of the file and any users not belonging to that group.

The right way to handle this would be to dig from somewhere the information, which users belong to that group (let's call this user set _U_). Then find out, which users have that file shared also directly (not via the group) and exclude those users from _U_. Finally, we could remove the file only from users left in _U_. All this is doable, but requires quite much effort.

**Comment by mmattel** [comment] 2017-09-20 13:15
hmmm confused...
Do I get it right that a file or mount is assigned to a user/group and not the other way round?
How I understand the above statement is, that if I unshare a file from a group everyone gets removed except the group members - more confused...
Is this a core or music behaviour ?

**Comment by paulijar** [comment] 2017-09-24 20:03
Sorry for the delay, I was offline for a few days. I didn't quite follow you, but this is how the sharing basically works in core/files:
1. When user A shares a file with user B, the file becomes visible in A's file list among A's own files.
2. If user A shared file with group G with members B, C, and D, the file becomes visible in file lists of B, C, and D.
3. It's also possible, that A shares the same file with user B and and group G={B, C, D}. In this case, user B has access to the file via two routes but the file is still visible in B's file list only once.
4. The user B, as the recipient of the shared file, may also unshare the file, making it disappear from his file list.
5. If a file is shared with group G={B, C, D}, and B unshares it, the file will still stay in file lists of users C and D.

As you can see from above, the sharing is quite complex concept with many different use cases. Fortunately, the Music app does not need to care about the details of sharing for most of the time. Basically, Music app does not know anything about groups or shares. When it scans for Music, it asks from core for all files visible to the user in question. It doesn't matter if those files are user's own files or shared with the user or shared with a group which the user belongs to. Then the app builds an index database from the metadata of those files.

The Music app has to care about shares only when they are unshared. When unshared, the file has to be removed from the index of the Music app for the user(s) who lost access to the file. This is triggered when the core sends to apps a signal like "file NNN unshared from user B" or "file NNN unshared from group G". Now, the problem are the cases where a file is unshared from group. The Music app doesn't know, which users belong to this group. Hence, it removes the file from the music database contents from *all* users, just in case. This causes the issue repoted here.

**Comment by mmattel** [comment] 2017-09-25 08:38
I do not know how it works in detail, but cant you use the usermanager from core to identify the group members and then continue with them?

**Comment by paulijar** [comment] 2017-09-25 09:33
Yes, most likely that's what we should do. After obtaining the list of group members, we should also remove the owner of the file from this list (if present). Ideally, we should also check if some of the group members have access to the unshared file via some other route (like having the file shared also directly to the user), and remove those from the list. Or maybe this last case is so special, that we don't need to worry about it.

Anyway, there's no principal reason, why this couldn't be fixed. It just requires some effort and so far it hasn't reached the top of my list of priorities.

**Comment by paulijar** [comment] 2017-10-08 12:00
Proper handling for unsharing from group is now implemented, and will be part of the next release (likely v0.5.3). 

There's still no special handling for the case where a file gets unshared from a group where user *A* belongs to, but user *A* has that file shared also directly with her. In such a case, *A* has to scan the unshared file again. I see no simple and efficient way to better handle this (probably quite uncommon) special case, and quite possibly any better handling might never be implemented.

**Closed by paulijar** 2017-10-08 12:00 UTC
Labels: Bug

**Comment by paulijar** [comment] 2017-10-15 19:00
The version 0.5.3 containing this fix was just released.
