### ISSUE TITLE
Sort by album uses the wrong tag to sort

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#586] opened 2017-09-25 17:00 UTC
When you sort by album, it gets sorted by composer. Ending up in multiple albums as you can see below. 
This happens when you have eg and album beeing a compilation of various artists

![image](https://user-images.githubusercontent.com/3321281/30820876-97fab108-a223-11e7-924b-ed52a11b7ceb.png)

![image](https://user-images.githubusercontent.com/3321281/30820724-12b05746-a223-11e7-9338-b8db30c47ec7.png)
![image](https://user-images.githubusercontent.com/3321281/30820757-2dcc7082-a223-11e7-8138-b56bb01043d4.png)

**Comment by paulijar** [comment] 2017-09-25 17:57
Have you put the composer info to the "artist" field of those files? Or in which field is it? Music app does not read the "composer" field of files at all, so certainly the composer name cannot come from there.

Anyway, if your album is a compilation from various artists, you should set the tag "album artist" in all the tracks belonging to the album. You can set it as "Various artists" or anything you like, as long as the album artist is the same for all the tracks.

**Comment by mmattel** [comment] 2017-12-28 14:57
Can´t you put all titles from an album together ? This would be logical.
Nobody will for sure change the tags working in eg iTunes just because of the music app... 😄

**Comment by paulijar** [comment] 2017-12-30 13:16
> Nobody will for sure change the tags working in eg iTunes just because of the music app... 😄

Well, I have modified my music files to contain the *album artist* tag on all compilation albums. Not because of the Music app but because of all the other music playing software I have been using before it. As I see it, this is kind of standard way of working and how the tags were supposed to be used (see e.g. https://mkoby.com/2007/02/18/artist-versus-album-artist/).

> Can´t you put all titles from an album together ?

You mean that we would kind of generate an artificial album artist by combining the track artists of all the tracks with identically named album? So if there is "Track A performed by Artists 1 on Album X" and "Track B performed by Artist 2 on Album X", we would group it like
```
Artist 1 & Artist 2
    Album X
        Track A
        Track B
```
This might be possible, but it would have couple of problems:
1. It is possible that many artists have similarly named albums but these should not be combined as one album. Think, for example, album named "The best of".
2. When we are scanning the music library, we are doing it sequentially file-by-file. We want to be able to throw the track to correct "bucket" based on the file itself alone. Having to change the album artist of a previously scanned file based on metadata from other tracks would complicate things quite a bit.

**Comment by mmattel** [comment] 2018-01-02 23:08
**Idea:**
Based on the fact that each folder has a unique name in his layer (unique ID) and each file has a same (unique ID), the following could be done:
All files in the same folder may belong to the same album, which is not a must, but a good and common seperator which can be used additionally in case of a conflict...

```
if empty (trim(file_tag [album_name])) { 
  if folder_name(file) = root { file_tag [album_name] =  unique_folder_ID }
  else { file_tag [album_name] = folder_name}
}

Album [album_name] = list {file_tag [album_name] with unique_folder_ID}
```
The thing that needs to be handled above is album_name naming when there are different unique_folder_ID´s ...

**Example:** extreme positions
1. An album may be a compilation of all different artists, composers ect. The only common things are the folder name and album_name
2. Everything is one folder and everything is distingusihed by ID3 tags only.
3. There are no tags in the file, at least no album_name
4. Same files / folders in different mounts

ad 1: easy ...
ad 2: the user MUST have a good naming and tagging to distinguish the content porperly
ad 3: take the foldername as album_name, if root folder give it a dummy name
ad 4: a mixture of 1-3

**Comment by mmattel** [comment] 2018-02-09 16:50
Did you had any time to think about this idea ?

**Comment by paulijar** [comment] 2018-02-11 21:52
I'm not sure if I completely followed all the details in your plan, but yes, it might be doable to use the folder structure as one input for some heuristic logic to deduce which tracks belong to the same album. I just have a feeling that fitting that kind of logic into the current existing codeline would not be all that easy.

**Comment by mmattel** [comment] 2018-02-12 11:18
You made a statement which was quite important: we can not rely if ID3 tags are present and all necessary tags filled or not.

We have following facts:
1. Music files are located in folder(s)
Means there is a storage ID, folder name and a file title - always !
This is a unique combination.
2. Music files can contain ID3 tags (Most important are Album, Title, Genre, CD (if there are more than one) and Cover)
3. You can have files with identical ID3 album names in the same folder - these belong most likely together
4. It can happen that there are differnt albums, with the same name in the same folder
This is a mess the user has created and is not specific to this app. It is the users responsibility to sort it out. 

To get the Album name for a track: 

CD_number[track] = get_the_cd_number(ID3:CD[track])  // create the right appendum text, can be empty
Album:name[track] = (empty(ID3:Album[track]) ? folder_name[track] : ID3:Album[track] . CD_number[track];

This info needs to be stored in the DB as part of the file info / tag info.

To get all files of an Album:
I suggest to start at the folder level and go down from there:
Show all files in the folder having the identical Album:name

I hope this make is a bit more transparent 😄

**Comment by paulijar** [comment] 2021-12-08 19:26
The Music app works as designed and the issue can be fixed with proper tagging. For all the mass-tagging needs, I can recommend the [Mp3tag](https://www.mp3tag.de/en/) software.

**Closed by paulijar** 2021-12-08 19:26 UTC
Labels: Needs info, 1 - Triaging
