### ISSUE TITLE
Blank spots in album view from same artist

### ISSUE THREAD

**Issue by M3talGuy** [owncloud/music#773] opened 2020-07-02 10:12 UTC
Hello,

i'm encountering this strange behaviour, where are blank spots rendered in the album view:

---
![grafik](https://user-images.githubusercontent.com/59865678/86345772-45a9f200-bc5c-11ea-82bd-5112b0c040ea.png)
---
![grafik](https://user-images.githubusercontent.com/59865678/86344857-19da3c80-bc5b-11ea-847f-8cc5ce6e183c.png)

This disappears when i zoom to 60%:

---
![grafik](https://user-images.githubusercontent.com/59865678/86344915-2e1e3980-bc5b-11ea-9bbd-d5fc23a005c5.png)

It only occours on 2 artists, where both have 8+ albums, but others with the same amount of albums, or more are fine. 

Im running:
Nextcloud 18.0.6
Music 0.14.1

Heres also some inspector output:
![grafik](https://user-images.githubusercontent.com/59865678/86369421-b3ffac00-bc7e-11ea-8e5c-ebcf355b6137.png)
![grafik](https://user-images.githubusercontent.com/59865678/86369383-a8ac8080-bc7e-11ea-96d5-e290f00acd5e.png)

(I would've used the issue [template](https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md), but the link to that reports a 404)

**Comment by paulijar** [comment] 2020-07-02 18:39
Thanks for the report. I have fixed this kind of issue already once, two years ago for the Music v0.8.0. My best guess is that it has now come back when Nextcloud has changed some font sizes. I couldn't reproduce the issue on the oldish Nextcloud instance where I have most of my test content. So probably I need to do some more testing using NC18.

At least the previous time, the root cause was that albums with less than 6 tracks got slightly smaller total height than the albums with 6+ tracks. The problem occurred when the album in the right-most column had smaller height than the one to left from it AND there were more albums on the next row. Exaggerating a lot, the layout engine then decided to place the albums like this:
![image](https://user-images.githubusercontent.com/8565946/86397356-5d10cb80-bcac-11ea-934c-5152159ebef8.png)

**Comment by M3talGuy** [comment] 2020-07-03 06:33
Thanks for your reply.

That seems about right. In all instances there are albums with less tracks above.
As i could've seen in the inspector output myself, the upper Album has a height of only 269, while the "normal" height is 279.4 px.

I upgraded from NC15 to 18 the other day and thats when i started noticing this. So you should be right about that.

**Comment by paulijar** [comment] 2020-07-10 10:28
This has been fixed in the Music app release v0.15.0.

**Closed by paulijar** 2020-07-10 10:28 UTC
Labels: Bug
