### ISSUE TITLE
"Invalid session token" for Ampache clients since Nextcloud 20 upgrade

### ISSUE THREAD

**Issue by gloomytrousers** [owncloud/music#791] opened 2020-10-17 14:23 UTC
Since (I think) the upgrade to Nextcloud 20, Power Ampache has failed to connect to the Music app. The error is:
> Ampache error
> code:401
> error: Invalid Login - invalid session token

I tried generating a new app password and using that, but got the same result.

I've also just installed AmDroid to try it; that gives "Error: Invalid Login - invalid session token" too.

The Nextcloud log contains lots of these (just a warning):
> {"reqId":"X4r9Dxf1VONOiH-9LhY3SwAAARQ","level":0,"time":"2020-10-17T14:17:51+00:00","remoteAddr":"xxxxxxxxx","user":"--","app":"twofactor_totp","method":"GET","url":"/nextcloud/index.php/apps/music/ampache/server/xml.server.php?auth=","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Dalvik/2.1.0 (Linux; U; Android 9; SM-G900F Build/PQ3A.190801.002)","version":"20.0.0.9"}

And one of these for each failing request:
> {"reqId":"X4r9Dxf1VONOiH-9LhY3SwAAARQ","level":0,"time":"2020-10-17T14:17:51+00:00","remoteAddr":"xxxxxxxxx","user":"--","app":"music","method":"GET","url":"/nextcloud/index.php/apps/music/ampache/server/xml.server.php?auth=","message":"Invalid Login - session token missing","userAgent":"Dalvik/2.1.0 (Linux; U; Android 9; SM-G900F Build/PQ3A.190801.002)","version":"20.0.0.9"}

This is with the latest release of the Music app, 0.16.0.

**Comment by paulijar** [comment] 2020-10-17 20:22
@gloomytrousers Thanks for the report. There seems to be a weird bug in Nextcloud 20, which I just reported for the server: One of the URL arguments from the Ampache client is eaten up by the Nextcloud server before it reaches the Music app. Without this argument, none of the Ampache API calls can work.

Which application is "AmDroid", or did you mean [Amproid](https://play.google.com/store/apps/details?id=com.pppphun.amproid)? Note that Music 0.16.0 does not support Amproid because it requires Ampache API v4.x, while Music currently implements API v3.5. This will change with Music v0.17.0 which should be released very soon.

**Comment by gloomytrousers** [comment] 2020-10-17 21:13
@paulijar thanks for the speedy reply - I'll watch the other bug.

AmDroid is https://github.com/Dejvino/amdroid installed from the f-droid app store for Android. It's pretty old actually - I just wanted another app to test with.

**Comment by stefangweichinger** [comment] 2020-10-19 07:07
Updated the Music App right now, I still get the "session token" error when I try to connect/sync via SubMusic on my Garmin Fenix 6X Pro:

https://github.com/memen45/SubMusic/issues/6

Yes, NC20.

**Comment by paulijar** [comment] 2020-10-19 08:01
@stefangweichinger Yes, updating the Music app doesn't help here because this issue is in the NC20 core.

**Comment by stefangweichinger** [comment] 2020-10-19 08:03
@paulijar Ah, I see, so I have to wait for https://github.com/nextcloud/server/issues/23544 to be fixed, right? thanks

**Comment by paulijar** [comment] 2020-10-19 20:07
@stefangweichinger Yes, nothing will happen to this bug before there is some resolution for nextcloud/server#23544. But once that will happen, I will post an update here, too.

**Comment by paulijar** [comment] 2020-12-02 19:41
If you are interested to monkey patch you Nextcloud installation, see https://github.com/nextcloud/server/issues/23544#issuecomment-736012528 for a possible solution. This comes with no guarantees, but it seems to fix the issue. Please report if you do this and notice any side effects.

**Comment by paulijar** [comment] 2020-12-22 21:51
The fix for the root cause of this problem has been merged to the `stable20` branch yesterday. I believe that this means that the fix will make it to the Nextcloud version 20.0.5 which is scheduled to be released on 2021-01-14.

**Comment by paulijar** [comment] 2021-01-15 21:15
The Nextcloud version 20.0.5 is now out and it has been verified that the Ampache API works on it. Closing.

**Closed by paulijar** 2021-01-15 21:15 UTC
Labels: Bug
