### ISSUE TITLE
Replaygain support

### ISSUE THREAD

**Issue by phirestalker** [owncloud/music#1008] opened 2022-09-03 23:02 UTC
I would like to have the built-in music player page to support adjusting the volume of songs based on their replaygain tags. Most of my playlists have songs from wildly different genres or years and therefore have varying loudness levels.

I know it seems like a lot to ask since I could just use a subsonic client. The problem is that there is not one single decent one for macOS that supports replaygain and works well.

**Comment by paroj** [comment] 2023-01-27 21:03
duplicate of #962

**Comment by paulijar** [comment] 2023-12-17 17:04
Closing as duplicate

**Closed by paulijar** 2023-12-17 17:04 UTC
Labels: Enhancement
