### ISSUE TITLE
Album view groups by artist

### ISSUE THREAD

**Issue by BigMichi1** [owncloud/music#1085] opened 2023-09-01 06:45 UTC
when i open the albums view it looks very misgrouped. sometimes it is grouped by album and sometimes by artist.

![image](https://github.com/owncloud/music/assets/91786/4248bd87-3be0-48a9-b7e4-8b10b8f0e4f0)

**Comment by paulijar** [comment] 2023-09-01 09:52
When you have albums with multiple artists tagged on different songs, then you should make sure, that all of those songs have also the tag *album artist* and this property has the same value on all of those songs. The value may be something which makes sense for that specific album, or you may just use "Various Artists" as is customary on compilation albums.

**Comment by paulijar** [comment] 2023-09-27 19:39
The issue may be solved with proper tagging and the app works as intended, closing.

**Closed by paulijar** 2023-09-27 19:39 UTC
