### ISSUE TITLE
Scan Hangs at 840 of 7012.  New issue or rehash of old issue?

### ISSUE THREAD

**Issue by tikidad** [owncloud/music#702] opened 2019-05-24 16:40 UTC
![image](https://user-images.githubusercontent.com/50923564/58343343-beffd000-7e20-11e9-9eca-2c3fadb64426.png)

I found some reports from 2016 of scanning issues but nothing since then.  This is a new Owncloud setup with the appliance version running in VirtualBox.  Accessing from Chrome.  I have reset the library and started a new scan but it always stops at 840.  If I restart it again without resetting it sits on 841 forever.  The music that has been identified can be played and playing music through the 'files" view works fine too.

**Comment by paulijar** [comment] 2019-05-25 19:34
Thanks for the report.

You could try to run the scanning from the command line interface. In the owncloud folder, run e.g.
`sudo -u www-data ./occ music:scan someusername`.
This method of scanning prints the file paths as it progresses through the files. This makes it easy to spot, what is the file where the scanning breaks. Additionally, you should check owncloud.log after the halted scanning. It might provide some additional details.

After finding the culprit file, please check if there's anything special on that file.

**Comment by thomas-merz** [comment] 2019-05-28 15:45
At my music library (external storage via webdav) it also hangs:  
9951 of 27452  
  
I already tried via occ-weg-console:  
occ $ music:scan thomas  

But without any significant change and without any useful hint in owncloud.log or in my case: nextcloud.log :-(

**Comment by paulijar** [comment] 2019-05-28 18:04
@thomas-merz The interesting part about the console scanning is the last file path which got printed. If the scanning always hangs on the same number, then it's likely that this particular file is causing the problem. To verify this, you could temporarily remove this file and see if the scanning can progress again.

But more importantly, you should check if there's anything special on that file. Maybe some unusual metadata or a file permission issue. When the triggering conditions are found, then we a big step closer to fixing this bug.

**Comment by tikidad** [comment] 2019-06-05 22:46
> Thanks for the report.
> 
> You could try to run the scanning from the command line interface. In the owncloud folder, run e.g.
> `sudo -u www-data ./occ music:scan someusername`.
> This method of scanning prints the file paths as it progresses through the files. This makes it easy to spot, what is the file where the scanning breaks. Additionally, you should check owncloud.log after the halted scanning. It might provide some additional details.
> 
> After finding the culprit file, please check if there's anything special on that file.

Thanks for the reply and sorry for my delay in response as I was out of town.  
The log file did not show anything useful...very little at all in fact.  When I initiate the scan it shows only 6 lines.  The first is this:  {"reqId":"x28Glq2ZJRRdjwa5izVt","level":3,"time":"2019-06-05T20:43:40+00:00","remoteAddr":"172.17.42.1","user":"owncloud","app":"PHP","method":"POST","url":"\/owncloud\/apps\/music\/api\/scan","message":"fseek() expects parameter 1 to be resource, null given at \/var\/lib\/univention-appcenter\/apps\/owncloud\/data\/custom\/music\/3rdparty\/getID3\/getid3\/getid3.php#2029"}

The others are similar.  My Owncloud version is the appliance running in Univention (in VirtualBox) so my owncloud path is not the same as your example CLI command and I have not been able to decode the occ command to run the scan from CLI in this setup.  (I am not a CLI guy...)  I have cleared the library and rerun the scan a few times and deleted the log file to reduce the noise and still get the same result and log.  Can you suggest the proper CLI command for this setup so I can try that route? Thanks!

**Comment by paulijar** [comment] 2019-06-06 17:09
Well, in my example, I didn't say anything about the path as the `occ` command was being run from current working directory `./`. I assumed that you had navigated to the correct directory first. So first, you should try to locate the directory where owncloud has been installed and move there. It's typically somewhere under `/var/www` directory.

The part `sudo -u www-data` in the command means that "run the following command as if I was the user named 'www-data'". The user name 'www-data' is probably the most common name used by the web servers. I believe that this is the default name at least with apache and nginx servers, but it is possible that your system uses some other name, too. You probably can figure the correct name out by checking, which user owns the files under the owncloud directory.

But if you can't or don't want to do this via CLI, you actually can find out the culprit file also from the log. First, you need to enable the debug logging. At least on ownCloud 10, this can be found from Settings > Admin > General > Log > What to log. From there, select "Everything (fatal issues, errors, warnings, info, debug)". Then rerun the scanning from the UI and download the log. Now, the log file should contain much more information, including the path of the file being scanned. After running the test, you should change the "What to log" back to what it was. Logging everything makes the log file grow rather rapidly even during normal daily use.

**Comment by paulijar** [comment] 2021-12-06 21:13
@tikidad @thomas-merz Are you still experiencing these issues on the latest version of the Music app? If yes, then can you locate the file where it hangs?

**Comment by thomas-merz** [comment] 2022-01-26 16:29
Sorry, I don't use the Music app anymore… 🤷‍♂️

**Comment by paulijar** [comment] 2022-01-26 20:08
As there's no way to know if the issue is still valid and no way to investigate any further without an example file, I'm closing the issue now. A new issue can be opened if anyone still runs into a problem like this.

**Closed by paulijar** 2022-01-26 20:08 UTC
Labels: Bug
