### ISSUE TITLE
music isn't compatible with the new version nextcloud 26

### ISSUE THREAD

**Issue by patachou74** [owncloud/music#1058] opened 2023-03-29 15:04 UTC
"query failed on server"

**Comment by patachou74** [comment] 2023-03-29 15:09
Hi,
Maybe can this help :
Erreur	index	Error: Class "OCP\AppFramework\Db\Mapper" not found

    /srv/nextcloud/lib/composer/composer/ClassLoader.php - line 578:

    include()

    /srv/nextcloud/lib/composer/composer/ClassLoader.php - line 432:

    Composer\Autoload\ClassLoader::Composer\Autoload\{closure}("*** sensiti ... *")

    /srv/nextcloud/apps/music/lib/App/Music.php - line 351:

    Composer\Autoload\ClassLoader->loadClass()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 171:

    OCA\Music\App\Music->OCA\Music\App\{closure}("*** sensiti ... *")

    /srv/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:

    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 138:

    Pimple\Container->offsetGet()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 487:

    OC\AppFramework\Utility\SimpleContainer->query()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

    /srv/nextcloud/apps/music/lib/App/Music.php - line 608:

    OC\AppFramework\DependencyInjection\DIContainer->query()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 171:

    OCA\Music\App\Music->OCA\Music\App\{closure}("*** sensiti ... *")

    /srv/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:

    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 138:

    Pimple\Container->offsetGet()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 487:

    OC\AppFramework\Utility\SimpleContainer->query()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 65:

    OC\AppFramework\DependencyInjection\DIContainer->query()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 331:

    OC\AppFramework\Utility\SimpleContainer->get()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 171:

    OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}("*** sensiti ... *")

    /srv/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:

    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 138:

    Pimple\Container->offsetGet()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 487:

    OC\AppFramework\Utility\SimpleContainer->query()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 65:

    OC\AppFramework\DependencyInjection\DIContainer->query()

    /srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 188:

    OC\AppFramework\Utility\SimpleContainer->get()

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 171:

    OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}("*** sensiti ... *")

    /srv/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:

    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    /srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 221:

    Pimple\Container->offsetGet()

    /srv/nextcloud/lib/private/AppFramework/App.php - line 171:

    OC\AppFramework\Utility\SimpleContainer->offsetGet()

    /srv/nextcloud/lib/private/Route/Router.php - line 315:

    OC\AppFramework\App::main()

    /srv/nextcloud/lib/base.php - line 1055:

    OC\Route\Router->match()

    /srv/nextcloud/index.php - line 36:

    OC::handleRequest()

**Comment by paulijar** [comment] 2023-03-29 18:08
Closing as a duplicate of https://github.com/owncloud/music/issues/1050. Will be fixed in the next release, hopefully within a couple of days.

**Closed by paulijar** 2023-03-29 18:08 UTC
