### ISSUE TITLE
Handle long artist names

### ISSUE THREAD

**Issue by icewind1991** [owncloud/music#424] opened 2015-09-05 13:33 UTC
While trying to scan my music collection it gives an exception because one song has an artist with a name longer than 256 characters which causes the query to insert the artist to fail.

The music app should trim the artist name to fit the column.

cc @MorrisJobke

**Comment by paulijar** [comment] 2017-04-01 21:22
I couldn't reproduce this with latest Music app sources, ownCloud 9.1.3 and mysql database. I tested with an mp3 file with 260 characters long album artist, track artist, track, and file names.

Either this has got fixed at some point or then the problem is specific to some database management system other than mysql.

**Comment by paulijar** [comment] 2017-10-10 13:50
@icewind1991 Is this old issue still present on your system? Or could this be closed?

**Comment by paulijar** [comment] 2017-11-11 17:42
Closing as there has been no reply for a month. Please file a new report if the issue is still reproduced on recent software versions.

**Closed by paulijar** 2017-11-11 17:42 UTC
Labels: Bug
