### ISSUE TITLE
[Feature Request] User specific compression options

### ISSUE THREAD

**Issue by DarkSide1305** [owncloud/music#954] opened 2022-03-13 20:12 UTC
User specific compression options would be amazing - that would allow me and others to create a User just for Music, so when im outside on Mobile data I can just log in to Nextcloud and start streaming all my Music without using up all my Data (I use high quality FLACs mostly)

**Comment by paulijar** [comment] 2022-05-29 08:50
This is basically duplicate of the longstanding feature request https://github.com/owncloud/music/issues/428

**Closed by paulijar** 2022-05-29 08:50 UTC
