### ISSUE TITLE
Music App Interferes with deleting files.

### ISSUE THREAD

**Issue by MagicMike123** [owncloud/music#802] opened 2020-11-07 17:41 UTC
I use the Music App for nextcloud for a long time now but suddenly it was breaking the ability to 
delete files.
The error message i got was:
[code]
Uncaught (in promise) TypeError: _.findWhere is not a function
at s.remove (merged-index.js?v=e1fdad8b-81:6207)
at s._removeCallback (filelist.js:150)
at Object. (jquery.js:3256)
at c (jquery.js:3099)
at Object.fireWith [as resolveWith] (jquery.js:3211)
at Object.Deferred.m.each.r. [as resolve] (jquery.js:3301)
at client.js?v=e1fdad8b-81:796
[/code]

After removing the Music app everything works normal again and no errors come up.

Happend with Nextcloud 19 and 20.
Thank you.

**Comment by paulijar** [comment] 2020-11-07 18:23
This is another duplicate of #798. Shall be fixed soon.

**Closed by paulijar** 2020-11-07 18:23 UTC
