### ISSUE TITLE
Error playing URL: /index.php/apps/music/api/file/XXXX/download

### ISSUE THREAD

**Issue by TwisX** [owncloud/music#916] opened 2021-11-10 13:31 UTC
When attempting to play any song, Nextcloud will immediately show this pop-up error:
"Error playing URL: /index.php/apps/music/api/file/XXXX/download", where XXXX is a different number for each song.
If I manually navigate to that URL, the Firefox media player will show, but playback will never start. If I right-click and save the page, it will successfully save the audio file.

I've reset the music collection to no avail. Tried with Chromium as well. Not sure if this is a general Nextcloud issue or an issue with the Music plugin itself.

Nextcloud version: 22.2.0 (Docker)
Firefox version: 94.0
Audio format: .m4a

None of the logs I've checked seem to have anything useful, but let me know if there's any additional info I could provide.

**Comment by paulijar** [comment] 2021-11-10 18:23
Can you see anything in the browser console (opened with the F12 key)?

If you click any audio file within the Files app, will it play, or does it have the same problem? In this case, the file is played via different URL but the logic on the browser side is the same, so answering this question may help us isolate the problem.

**Comment by TwisX** [comment] 2021-11-12 21:07
> Can you see anything in the browser console (opened with the F12 key)?
> 
> If you click any audio file within the Files app, will it play, or does it have the same problem? In this case, the file is played via different URL but the logic on the browser side is the same, so answering this question may help us isolate the problem.

Thanks for the response. Just now went to check and everything has started working. Maybe it took a while to sort through everything in the background? My library is 5,000+ songs if that matters.

**Comment by paulijar** [comment] 2021-11-12 21:31
> Maybe it took a while to sort through everything in the background?

There should be now such effect; everything should be ready once the scanning has been finished and the songs are shown. Also 5000+ songs isn't yet on the extreme limits of the app, it should be able to handle at least 10 times that large libraries (although most of my testing has been done on a library with only 2000+ songs).

Now, being unable to play any songs at one particular time could be explained with a user session which has expired. There is such a shortcoming on the Music app, that it can't automatically direct the user back to the login page in case the session is not valid. But that should get fixed by reloading the web page and you probably already tried that. And if you experienced the same issue also on another browser, then that pretty clearly rules out any session related problems.

**Comment by TwisX** [comment] 2021-11-12 21:34
> > Maybe it took a while to sort through everything in the background?
> 
> There should be now such effect; everything should be ready once the scanning has been finished and the songs are shown. Also 5000+ songs isn't yet on the extreme limits of the app, it should be able to handle at least 10 times that large libraries (although most of my testing has been done on a library with only 2000+ songs).
> 
> Now, being unable to play any songs at one particular time could be explained with a user session which has expired. There is such a shortcoming on the Music app, that it can't automatically direct the user back to the login page in case the session is not valid. But that should get fixed by reloading the web page and you probably already tried that. And if you experienced the same issue also on another browser, then that pretty clearly rules out any session related problems.

Yeah, I don't think it had anything to do with my user session either. Just glad that it's working now. I'll report back if the issue occurs again. Thanks.

**Comment by Doofitator** [comment] 2021-11-13 07:59
I'd like to drop in and say that I'm getting the same error - could it be due to the codec? Some tracks (such as those with AAC or MP3 codecs) work fine, but others (eg. ALAC) throw the error (in my browser, as per #810)

**Comment by biguenique** [comment] 2021-11-18 05:50
I get those pesky `Error playing URL: /index.php/apps/music/api/file/xxxxx/download` notifications, but *midway through* almost every track. The inspector console shows `GET https://domain.com/index.php/apps/music/api/file/xxxxx/download 400`, then song stops and the player skips to the next one. Pretty annoying!

All song are quite regular MP3s. Web server is OpenLiteSpeed. Nextcloud tends to work A1 otherwise.

**Comment by paulijar** [comment] 2021-11-18 20:36
@biguenique If you look at any one file with the problem, then does it always happen at the exact same time offset within the file or is it random? If you download the file to your PC and then open it to the web browser from the disk, does it then play without problems?

**Comment by CiaranGruber** [comment] 2021-11-23 04:02
Also, just thought I'd add a few details of my own and the troubleshooting steps I did since the issues are also present on my Nextcloud installation and they may be helpful.
- MP3 and FLAC files work fine but not M4A (I'm unsure about other formats)
- Rebooting the server did not fix the issue, nor did uninstalling and reinstalling the app
- Everything client-side and server-side is updated to the latest versions (ie. Browsers and Nextcloud installations, etc)
- I've tested on Firefox and Chrome and both don't work
- If I download the song and play it on my computer it plays as expected
- I have also tried the alternative app 'Audio Player' on Nextcloud and that one also failed to play the M4A files
- The only error I get is the one mentioned in the title of the issue
- I do also have about 2000 songs however I doubt this could be the cause
- Very large MP3 files still run as expected so filesize is probably not the issue
- Most of the other issues mentioned in previous comments are also present

As for errors in the Console window in the Browser the following (relevant ones) came up when trying to play a broken file:
- `Using html5 for type audio/mp4 URL remote.php/webdav/XXX`
- `Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://XXX.com/apps/music/dist/webpack.files_music_player.d31c71cd10eada56930a.js?v=3b3a29ba-7
Source Map URL: webpack.files_music_player.d31c71cd10eada56930a.js.map`
- `Media resource https://XXX.com/index.php/apps/music/api/file/XXX/download could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR`
- `HTML5 audio: sound load error`
- `Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.`

**Comment by paulijar** [comment] 2021-11-23 20:34
@CiaranGruber Are your M4A files ALAC encoded as those are known to be not supported on the major browsers (as mentioned above in https://github.com/owncloud/music/issues/916#issuecomment-967801209)? You said you downloaded the file and could play it on your computer, but did you try to open the local file on the browser? If the browser can't play the track, then there's basically nothing the Music app can do. But if the browser plays the local file, then this is a more interesting case.

**Comment by CiaranGruber** [comment] 2021-11-24 12:34
Ah OK, I missed what was said in the previous comments, it does appear that the encoding was the issue as they were all ALAC encoded. As a result, attempting to play a local file within the browser caused it to fail. Perhaps a solution could be if there's a library that can play ALAC files on modern browsers however this may not be possible without being quite resource-intensive

**Comment by Mte90** [comment] 2022-01-16 15:00
I have the same issue:

![immagine](https://user-images.githubusercontent.com/403283/149665353-72a3ad5c-e486-48f0-9660-12361d4e8b86.png)

I get the warning in console that was not able to elaborate the music file but the URL opening in Nextcloud worked and show a player inside Firefox.
![immagine](https://user-images.githubusercontent.com/403283/149665430-63d6906c-da42-4336-a356-cf04f727bb19.png)
This is the full error list that I guess can help improving the JS code.

**Comment by paulijar** [comment] 2022-01-16 19:50
@Mte90 You are apparently trying to play an MP3 file so obviously your problem is not related to M4A/ALAC files as with some of the commenters here. Do you see this problem systematically on all of your files?

You said that opening the URL showed a player within Firefox. I assume that you meant that URL `<domain>/index.php/apps/music/api/file/25404/download`. Does this player also play the file, or do you get similar errors there?

**Comment by Mte90** [comment] 2022-01-17 09:59
Right now happens with all the files I have in Music that are all MP3.

> You said that opening the URL showed a player within Firefox. I assume that you meant that URL `<domain>/index.php/apps/music/api/file/25404/download`. Does this player also play the file, or do you get similar errors there?

The player play the file with no errors.

**Comment by paulijar** [comment] 2022-02-06 16:01
@Mte90 Sorry for the long delay, but I really have no explanation of what is going on in your case. If the file plays fine when opened directly from the download URL to Firefox, then that already proves two things: Your server is streaming the file properly and your Firefox installation is able to play a file like that. And yet, the message `Error Code: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e00b) Details: OnMediaSinkaAudioError` in the console suggests that Firefox couldn't play the file for some reason. There is very little playback-related logic in the Music app itself, we basically just ask the browser to play the file from the given URL.

**Comment by Mte90** [comment] 2022-02-07 09:14
In the meantime I don't see anymore the error. Maybe nextcloud updates or browser fixed the issue.

**Comment by paulijar** [comment] 2022-11-13 20:52
There has been multiple issues with similar symptoms discussed here and it's not clear if any of them were actually caused by the Music app. Also, most of them have apparently got solved one way or another. I'm closing the issue now; please open new issues if you still run into problems like this.

**Closed by paulijar** 2022-11-13 20:52 UTC

**Comment by ZenKyma** [comment] 2023-07-27 12:09
I had the same issue today.

Turned out that mixxx was still open and occupying the audio outputs of my ASIO driver lol. Realized only when I tried to opened a track offline.
