### ISSUE TITLE
cannot specify path to music folder

### ISSUE THREAD

**Issue by samosquito** [owncloud/music#863] opened 2021-06-03 18:13 UTC
### Steps to reproduce
1. Installing the music app
2. Go to settings
3. Try to put in the path to any folder

### Expected behaviour
Should be able to select a path to any folder, e.g. /Data/Media/Musik/mp3...

### Actual behaviour
By clicking in path field, an error ocures: Fehler beim Laden der Dateiauswahlvorlage: {error}

### Server configuration
**Operating system**: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-generic x86_64) 

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** PHP 7.4.3 (cli)

**Nextcloud version:** 21.0.2

#### Browser log
```
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://....de/apps/comments/js/comments-app.js?v=e759b388-19
Source-Map-Adresse: comments-app.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://....de/core/js/dist/main.js?v=e759b388-19
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/files_sharing/js/dist/main.js?v=e759b388-19
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/accessibility/js/accessibilityoca.js?v=e759b388-19
Source-Map-Adresse: accessibilityoca.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/user_status/js/user-status-menu.js?v=e759b388-19
Source-Map-Adresse: user-status-menu.js.map?v=dc26003b86c12464c63a

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/core/js/dist/files_client.js?v=e759b388-19
Source-Map-Adresse: files_client.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/files_videoplayer/js/main.js?v=e759b388-19
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https:/...de/core/js/dist/unified-search.js?v=e759b388-19
Source-Map-Adresse: unified-search.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/music/dist/webpack.app.4edf41907fd4207c4fe7.js?v=e759b388-19
Source-Map-Adresse: webpack.app.4edf41907fd4207c4fe7.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/apps/notifications/js/notifications-main.js?v=e759b388-19
Source-Map-Adresse: notifications-main.js.map?v=a6200f901dc23686c1c2

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://...de/core/js/dist/files_fileinfo.js?v=e759b388-19
Source-Map-Adresse: files_fileinfo.js.map

1

​

**Comment by paulijar** [comment] 2021-06-05 15:18
Thanks for the report. However, I can't seem to reproduce the issue. I just installed NC21.0.2 to verify with the same version.

The folder selection dialog we use here comes from the host Nextcloud (or ownCloud) server, so I wonder if your server installation is now somehow corrupted. The (more or less) same dialog is used in the Files app for moving and copying. Does it work, if you navigate to the Files and press the "..." icon on some file and select the option "Move or copy"?

**Comment by samosquito** [comment] 2021-06-05 22:07
Okay, that seems bad. Using copying/moving in the files App gives me exactly the same error

**Comment by paulijar** [comment] 2021-06-07 18:19
Alright, then we know that the problem almost certainly is not in the Music app. If you want to make extra sure, you could temporarily disable the Music app and test the "Move or copy" again.

But assuming that the problem is in the Nextcloud server, maybe reinstalling the server would help.

**Comment by samosquito** [comment] 2021-06-09 19:16
Okay, thanks for help. Now we're in the wrong place with this issue, but before reinstalling nextcloud: Is it possible to identify the issue with other logs?

**Comment by paulijar** [comment] 2021-06-09 19:44
I doubt it. This seems like a front-end issue, so the browser console is all there is. You could of course check nextcloud.log on the back-end, but probably there will be nothing of interest this time.

If you would report this to the Nextcloud server github https://github.com/nextcloud/server/issues, then I guess there is a chance that someone knowing that side better would have some insight. But there is also a chance that the report just gets buried among the thousands of other reports. I suspect, that the inflow of reports on that side is so high that reports with no known steps to reproduce might easily get disregarded.

**Comment by paulijar** [comment] 2021-06-27 11:04
Closing as this does not seem to be an issue with the Music app itself.

**Closed by paulijar** 2021-06-27 11:04 UTC
