### ISSUE TITLE
Change CHANGELOG to 'Keep a changelog' format

### ISSUE THREAD

**Issue by siccovansas** [owncloud/music#824] opened 2021-02-14 22:26 UTC
It would be awesome if the current changelog format is changed to the 'Keep a changelog' format. [Nextcloud recommends this](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog) for its apps. A benefit is that the entry of the most recent version is shown in the 'Apps' section of a Nextcloud installation. This makes it easy for admins to see what's new :)!

I'd be happy to create a PR to change the format. Some instructions about what to change would be nice. Some notions/questions:
- Change `CHANGELOG` to `CHANGELOG.md`
- The main change would be the version info from `v1.0.1 2021-02-13` to `## 1.0.1 - 2021-02-13`
- Make the newline usages consistent with the spec
- I'd leave the different style versions like `0.2` and `0.1-alpha` the same
- Change the `*` to `-`, but what to do with the indented lines? I'm not sure if this follows the format, but I guess it doesn't matter much

**Comment by paulijar** [comment] 2021-02-15 07:31
Thanks for the info and a PR is welcome.

I guess that the second level bullets can be kept as `*` since it's anyway valid markdown syntax. And actually, it will make it easier to read as raw text when the first level and second level bullets use different styles.

I'm not sure what you meant about the newline usage. Where, exactly, does it deviate from the spec as of now?

**Comment by paulijar** [comment] 2021-02-15 07:52
Btw, I just noticed a bug in the current version of the Music app, and I assume that I need to release 1.0.2 soon (although I haven't yet investigated the issue throughoutly). But if the PR doesn't make it in time for 1.0.2, then there's of course new releases coming later.

**Comment by siccovansas** [comment] 2021-02-15 16:45
Great! The changes are in PR #827.

Regarding the newlines, there were some unnecessary newlines in early releases. Not a big deal :).

**Comment by paulijar** [comment] 2021-02-15 19:34
The PR has been merged, case closed!

**Closed by paulijar** 2021-02-15 19:34 UTC

**Comment by paulijar** [comment] 2021-02-18 21:48
Music v1.0.2 is now out, and the changelog now shows up in the Nextcloud app management as intended.

**Comment by siccovansas** [comment] 2021-02-19 10:05
Awesome, thanks!
