### ISSUE TITLE
[Feature Request] ID3Tag Editing

### ISSUE THREAD

**Issue by sltmunky69** [owncloud/music#1072] opened 2023-06-22 18:51 UTC
This would be nice to do without having to use an external app. I could also see this as being a candidate for an add-on plugin for the music app, so I won't hold my breath.

**Comment by paulijar** [comment] 2023-07-02 10:10
Closing as duplicate of https://github.com/owncloud/music/issues/729.

**Closed by paulijar** 2023-07-02 10:10 UTC
