### ISSUE TITLE
Unable to generate API Password for Ampache and Subsonic

### ISSUE THREAD

**Issue by raxp122** [owncloud/music#1038] opened 2023-01-02 11:09 UTC
After writing a name for the new API Password clicking the button returns: "Failed to generate new Ampache/Subsonic password" without any other context.

**Comment by paulijar** [comment] 2023-01-02 13:27
Thanks for the report. I could reproduce this on Nextcloud 17 but not on Nextcloud 25; I didn't test any other cloud versions yet. The root cause is not yet clear but it's probably something simple once I get the chance to look into it.

**Comment by Bendelk** [comment] 2023-01-02 14:20
> Thanks for the report. I could reproduce this on Nextcloud 17 but not on Nextcloud 25; I didn't test any other cloud versions yet. The root cause is not yet clear but it's probably something simple once I get the chance to look into it.

**Comment by paulijar** [comment] 2023-01-02 21:55
On Nextcloud, this seems to affect at least NC23 and older versions but not NC25. I haven't tested NC24. On ownCloud, at least OC10.0 is affected but 10.4 or 10.6 or 10.11 are not.

Anyone in a hurry should be able to fix this by removing the following line of code from their installation:
https://github.com/owncloud/music/blob/65fd87b31b1726a36a7008583eff4870be64c757/lib/Controller/SettingController.php#L150

With the `@CORS` attribute removed, it will become impossible to generate API keys from external sites (as has been the original intention of the API in question) but the chances are that you would not do that anyway. I don't know if anyone ever has.

**Comment by raxp122** [comment] 2023-01-03 08:56
To give a bit more context i was on NC 24.0.8 so i tried upgrading to NC25 and all is working fine.

**Comment by paulijar** [comment] 2023-01-08 19:32
This is now fixed in the Music release v1.8.1.

**Closed by paulijar** 2023-01-08 19:32 UTC
Labels: Bug
