### ISSUE TITLE
Cannot modify header error every time I click play

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/music#442] opened 2015-11-02 21:24 UTC
When I click play (and not until I click play) in the music app I get this error in my logs:

```
Cannot modify header information - headers already sent by (output started at /PATH/TO/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /PATH/TO/owncloud/3rdparty/sabre/http/lib/Sapi.php#63 
```

I'm using nginx, ownCloud 8.2, arch linux, mariadb on the server and firefox 41 on Arch linux client side.

Possibly related to these issues with similar errors in the log:
https://github.com/owncloud/music/issues/404
https://github.com/owncloud/calendar/issues/903
https://github.com/owncloud/android/issues/1074

**Comment by MU7L3Y** [comment] 2015-12-01 21:35
I get that too. Refer: https://github.com/owncloud/music/issues/297

**Comment by paulijar** [comment] 2017-10-15 17:31
@Bugsbane This report is almost two years old and a lot has changed since. Also, all the "possibly related" issues are already closed. Is this problem still valid for recent versions of the Music app and ownCloud/Nextcloud?

**Comment by paulijar** [comment] 2017-11-11 17:41
Closing as there has been no reply for almost a month. Please file a new report if the issue is still reproduced on recent software versions.

**Closed by paulijar** 2017-11-11 17:41 UTC
