### ISSUE TITLE
Bug: Each link goes back to the top of the page

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#311] opened 2014-11-11 16:35 UTC
### Steps to reproduce
1. Click on a link

### Expected behaviour
Just play the song.

### Actual behaviour
The song is played, but the page gets scrolled back to the top of the page.
That's kind of annoying when you're searching for a song ;)

### Server configuration
**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 33

**Operating system:** GNU/Linux (Archlinux), Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paulijar** [comment] 2016-09-14 18:54
This seems to be duplicate of #364 (or vice versa since this one is older).
cc @gnarula

**Closed** 2016-09-14 19:35 UTC
Labels: Bug
