### ISSUE TITLE
Music page is blank

### ISSUE THREAD

**Issue by azmeuk** [owncloud/music#588] opened 2017-10-04 19:34 UTC
Nextcloud 12.0.3
Music 0.5.2

Hi. I have a very large music collection (50k+) The `music` page of my nextcloud installation is blank.
Looking at the requests the page made, I can see that the `collection` and `scanstate` api calls returned 500 codes.
In my apache logs I found the following lines:
```
[Wed Oct 04 21:29:36.569376 2017] [:error] [pid 60340] [client 192.168.1.98:50406] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 173
[Wed Oct 04 21:29:44.019251 2017] [:error] [pid 59641] [client 192.168.1.98:50414] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 173
[Wed Oct 04 21:30:16.526579 2017] [:error] [pid 59644] [client 192.168.1.98:50404] PHP Fatal error:  Call to a member function getNameString() on null in /var/www/nextcloud/apps/music/db/track.php on line 103
[Wed Oct 04 21:30:20.213683 2017] [:error] [pid 22460] [client 192.168.1.98:50410] PHP Fatal error:  Call to a member function getNameString() on null in /var/www/nextcloud/apps/music/db/track.php on line 103
```
The last two lines seem to be about the music app.

**Comment by paulijar** [comment] 2017-10-04 20:09
Thanks for the report. The app probably does not scale well for music collections larger than some 10k tracks, and the problem is probably somehow related to this. But even if the UI would show up correctly, I'm afraid that it would be too slow to be usable with a collection that large.

Has the page been blank from the beginning or did the application first start scanning and then the page was left bank? Did the scanning seem to finish?

**Comment by azmeuk** [comment] 2017-10-05 16:17
Actually the page is not totally blank. There is the header and the activity icon, but it never stops.

![music](https://user-images.githubusercontent.com/60163/31238178-66e2ff16-a9f9-11e7-92a6-7b1d030a4527.png)

**Comment by paulijar** [comment] 2017-10-05 19:00
If the app never showed the "Scanning files" box, then one possible reason is that executing the `scanstate` api call took too much time on the server and timed out. Within that call, the app fetches a list of audio files which have not yet been indexed. If you have lot of files in general in your cloud, filtering the list might take some time. If you have lot of non-audio files, then It *might* help to set the "Path to your music collection" under the Personal settings so that it contains only the audio files.

Also, if you have access to the command line, then you may try to do the scanning with the occ tool, e.g.
```sudo -u www-data ./occ music:scan your_username```

**Comment by azmeuk** [comment] 2017-10-05 21:10
I actually did the command line scanning before posting this bug report. I did not know about the "Path to the music collection" settings, I am giving it a try and let you know.

**Comment by paulijar** [comment] 2017-10-06 19:00
Ah, if the collection is already scanned, then it probably doesn't matter even if the `scanstate` times out. The real issue might be that `collection` endpoint times out. Sadly, I have no easy fix for that. I would need to experiment with such a large collection but building one is not all that simple.

**Comment by azmeuk** [comment] 2017-10-08 13:22
Would it help if I wrote a script that generates a collection of dummy audio files (with real metadata, but without music) ?

**Comment by alnixon** [comment] 2017-10-09 12:04
I have experienced a similar issue and, from what I can tell, it is down to the DOM being overwhelmed with rendering so much data.
I believe a deferred loading technique would resolve this issue, similar to that demonstrated here: https://material.angularjs.org/latest/demo/virtualRepeat
I did play around with writing my own a few weeks ago and it did improve performance dramatically.  There was still a lot of work required to make this anywhere near release ready but it proved the concept and demonstrated to myself that this would resolve this issue.

**Comment by paulijar** [comment] 2017-10-09 17:23
@azmeuk I managed to create a collection of 58625 tracks by making the bulk of the collection to be copies of one 100 KB music file, distributed in many folders. This isn't quite realistic collection as there are only a few artists and 558 albums but I guess that the number of tracks is still the most important factor.

With this setup, I could see that creating the collection.json timed out after 60 seconds. I did some digging but couldn't find, where this 60 s limit comes from or how to prolong it. On timeout, the `collection` endpoint returned error code 504. You reported that the endpoint returned 500 and there were also some errors in the log which I haven't seen. So your issue may still be different than what I witnessed.

It also seemed to me that the time taken to build the collection.json was just around the critical limit of 60 s on my low-end server. With few small optimizations, I could push it down to 50 s and after this the UI started working. It's possible I could still squeeze some seconds off this. This of course is not a generic solution for the problem; it just pushes the size cap of the music collection a bit upwards. Also, if the server was burdened with other tasks during the collection building, then it again took more than 60 s and timed out.

One thing to note is that the collection.json building happens only the first time `collection` endpoint is called after updating the music database. After successful build, the result is cached and next calls to `collection` take only few seconds. One possible workaround could be to add the building and caching of the collection.json to the `occ music:scan` command. Then the owners of large collections would just need to rerun `occ music:scan` every time they change their collection in any way which would be somewhat cumbersome.

The right way to fix this would be to get rid of the one monolithic collection.json and load the contents more on-demand basis. This, however, would be rather large conceptual change and I'm afraid I don't have time to implement such any time soon.

**Comment by paulijar** [comment] 2017-10-09 17:34
@alnixon Your issue is related but not exactly the same: When the front-end gets overwhelmed by the size of the collection, it takes lot of time to render the UI but eventually it should appear. In the issue reported here, the problem is on the back-end and the front-end never gets any content to render.

I have done a bit of investigation on those virtual-scroll-thingies but it seems to me that they always require the repeated elements to be of same static height. This is a bad fit for the design of the Albums view of the Music app. For the playlists and the 'All tracks' view, the virtual scrolling would be a good alternative and applying it there has been on my mental to-do list for some time.

**Comment by paulijar** [comment] 2017-10-15 19:08
@azmeuk Music app version 0.5.3 was just released with slightly improved performance on serving the `collection` and `scanstate` endpoints with large libraries. If you can give it a try, I would be interested to hear if it helped at all in your case.

**Comment by azmeuk** [comment] 2017-10-15 22:01
scanstate returns a 200, but collection still returns a 500. I can also see a message in the header bar telling that there is a problem with the server.

**Comment by paulijar** [comment] 2017-10-16 19:00
@azmeuk Okay, thanks for the info. I just added that error banner there in 0.5.3, and it's popped up if fetching `collection` fails. I figured that this is better than spinning the loading indicator forever.

Do you see the the same error messages in the log as previously? The message "Call to a member function getNameString() on null" indicates that there was a track object which didn't have parent album object set. This kind of situation shouldn't really happen, there should always be at least the "Unknown album" object assigned for each track. I wonder if something has gone wrong already in the scanning phase when building the music database. Was there any errors in the log during the scanning?

**Comment by azmeuk** [comment] 2017-10-17 16:13
I can see the following error in the nextcloud logs:

> Error	index	Error: Call to a member function getNameString() on null
> 
>     /var/www/nextcloud/apps/music/controller/apicontroller.php - line 192: OCA\Music\Db\Track->toCollection(Object(OC\L10N\L10N))
>     /var/www/nextcloud/apps/music/controller/apicontroller.php - line 111: OCA\Music\Controller\ApiController->buildCollectionJson()
>     [internal function] OCA\Music\Controller\ApiController->collection()
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Music\Controller\ApiController), 'collection')
>     /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Music\Controller\ApiController), 'collection')
>     /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ApiController', 'collection', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
>     [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
>     /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
>     /var/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/music/api...')
>     /var/www/nextcloud/index.php - line 48: OC handleRequest()
>     {main}
> 
> 	2017-10-17T18:07:54+0200
> Error	PHP	Undefined offset: 613853 at /var/www/nextcloud/apps/music/controller/apicontroller.php#178	2017-10-17T18:07:54+0200

**Comment by paulijar** [comment] 2017-10-19 19:31
@azmeuk From these logs, it seems to me that for some unknown reason the artist of the track does not exist in the database. Apparently, the track defines the artist ID as 613853, but such artist is not found. Could you check directly from the database if there is such artist, and if there is anything special in the track in question? You could use queries
```
select * from oc_music_artists where `id` = 613853;
```
and
```
select * from oc_music_tracks where `artist_id` = 613853;
```

**Comment by azmeuk** [comment] 2017-10-19 20:15
```
MariaDB [nextcloud]> select * from oc_music_artists where `id` = 613853;
Empty set (0.01 sec)
MariaDB [nextcloud]> select * from oc_music_tracks where `artist_id` = 613853;
+--------+---------+-----------------------------------------------------------------------------------------------------------+--------+------+-----------+----------+--------+---------+---------+-----------+------+
| id     | user_id | title                                                                                                     | number | year | artist_id | album_id | length | file_id | bitrate | mimetype  | mbid |
+--------+---------+-----------------------------------------------------------------------------------------------------------+--------+------+-----------+----------+--------+---------+---------+-----------+------+
| 307018 | azmeuk  | Daft Punk - Alive 2007 Deluxe Edition (Disc 1) - 05 - Around the World - Harder, Better, Faster, Stronger |   NULL | NULL |    613853 |   306997 |    343 |   50979 |  377076 | audio/ogg | NULL |
+--------+---------+-----------------------------------------------------------------------------------------------------------+--------+------+-----------+----------+--------+---------+---------+-----------+------+
1 row in set (0.00 sec)
```

**Comment by paulijar** [comment] 2017-10-19 20:49
Okay, thanks. This confirms my earlier assumption. Now the only question is that how the database has ended up in such a broken state. Is there anything special in the artist of that track? Maybe some special characters or unusually long name or something?

**Comment by azmeuk** [comment] 2017-10-20 12:52
I just sent you the faulty file by email!

**Comment by paulijar** [comment] 2017-10-20 18:00
There doesn't seem to be anything wrong with the file: when I uploaded it to my cloud, it got indexed correctly and the Music app started up fine. Something else has broken the database.

One possibility appeared to my mind: There is a cleanup task in the Music app which runs every 15 minutes (IIRC). One thing it does is to clean up albums and artists which don't have any tracks. Now, with unlucky timing, it could happen that the cleanup runs during the scanning just after a new artist has been added to the DB but before the first related track has been added. In this scenario, the artist would be removed and the track would be left with invalid artist_id. I don't know if this is what has happened, but it is certainly not impossible. And the probability for such incident would be greater on larger music libraries.

One thing you could try would be to rename the music file causing the problem. This should trigger database update on that particular file. You can then give it the original name again if you like. I assume that this should fix the inconsistency in the DB. Then the Music app would either start working or you would stumble upon the next inconsistent track if there are more.

**Comment by paulijar** [comment] 2017-11-10 21:06
@azmeuk Did you try renaming the incorrectly indexed file as I suggested above? Did it help?

Anyway, you could test the brand new Music app release v0.5.4. There, any tracks with inconsistent data in the DB are skipped when showing the music library, so the whole app should no longer break on such incident. The skipping happens silently, but you can see from the log if files have been omitted for this reason.

**Comment by azmeuk** [comment] 2017-11-13 20:19
Hi. After renaming the faulty file and upgrading to v0.5.4 I still get a 500 and no music. The log generated by this error is HUGE, I just sent it by email. I am sorry I could not extract the useful parts.

**Comment by paulijar** [comment] 2017-11-13 21:48
@azmeuk Thanks. The log shows that there are around 35 more tracks which refer to non-existing album or artists. Hence, renaming the one file did not help much. However, this is no longer the main issue as the app can now skip those tracks with inconsistencies. Now the things break down because the created collection json is so large that it cannot be inserted to the cache which is maintained in the database table oc_music_cache. The error message states "The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.".

**Comment by azmeuk** [comment] 2017-11-13 22:26
Ok. Setting the following code in my `my.cnf` configuration file solved the 500 code problem.
```
[mysqld]
innodb_log_file_size = 256M
```
Now I can see the `collection` request returns a nice 200 code is 13M heavy. (Also there is no 304 code for this request when I reload the page).

The bad news is: there is no music. The interface looks exactly like my previous screenshot.

**Comment by paulijar** [comment] 2017-11-14 17:24
At least we are making progress here but sorry to hear that it still doesn't work. So the spinning progress indicator is again shown indefinitely and the UI doesn't change even if you wait for several minutes?

Is there anything now in the browser console?

**Comment by azmeuk** [comment] 2017-11-14 17:57
So maybe I did not wait long enough. Now I can see data! \o/ but the UX is really slow (even for a modern computer), almost frozen. This is too bad, it is definitely unusable at this point :(

I noticed this message in the console:
```dom surveyor shutting down: too many misses - contentscript.js:1305:9```

Thanks anyway!

**Comment by paulijar** [comment] 2017-11-15 18:48
Okay, thanks for the info. Which browser are you using? According to my tests, Firefox remains a bit more responsive under large collections than Chrome or Edge. Chrome, on the other hand, loads the application view faster than other browsers. With 50k+ tracks, also Firefox UI is definitely slow but it might be barely usable while other browsers are not. But overall, it's fair to say that the Music app scales really badly to collections that large.

**Comment by paulijar** [comment] 2017-11-16 16:59
To update my previous comment, today was released a new Firefox version 57.0 (aka  "Quantum"), at least for Windows. This version performs significantly better on large libraries than any previous versions.

**Comment by Biont** [comment] 2017-11-28 14:22
I started to see the same problem today. Here is a pastebin of the exception I found in the logs: https://pastebin.com/RXg5GcCC

Right before this log entry, I also had an ```An exception occurred while executing 'INSERT INTO `oc_music_cache```` error along with an incredibly large data set of what appears to be my entire music collection.

It's not even THAT big yet, though: Just about 1450 files.

In my case, it complained about a ```Got a packet bigger than 'max_allowed_packet' bytes``` which I could "fix" by increasing it from 1M to 5M. I really do not want to have to do that because I think SQL inserts that large are a sign of "doing it wrong".

Am I reading right that you are generating a collection.json containing the *entire* music collection and then push it to the database? I have yet to dig into NextCloud code, but if it has to be a single JSON file, is there no way to just serve it as a static file? Can't you create a "hidden" folder inside the user's storage for this kind of metadata? I see a lot of NC apps do this kind of thing, but maybe there are better recommended ways to store static files on a per-user basis for internal usage.

Then I noticed you're putting base64'd images into the JSON file which of course bloat it up immensely. I know you can get single cover images via the REST API, so can't you just store an ID (or the full URL) and lazy-load it when it actually needs to be displayed? This would probably help postpone the inevitable MySQL crash quite a bit since it would trim down the size of the JSON file to ~40%.

**Comment by Biont** [comment] 2017-11-28 14:45
Regarding the album art, I found this commit, which introduced embedding of album-art in the collection, even mentioning the increased collection.json: 7d139a628430f552c1a8e264cb3caa89aa2a394f

Maybe this needs revisiting. For one, I don't get why Chrome would be unable to cache the album art. If everything fails, even throwing the base64 in localStorage would be a viable option. Second, I don't think you can handle large collections properly without splitting up data wherever possible/feasible. Can we maybe revert the old functionality (or at least get an option to do so?)

**Comment by Biont** [comment] 2017-11-28 16:42
I found a very quick hack to "restore" the previous method by editing ```Album::coverToCollection()``` and loading those covers one by one indeed takes quite a long time. Is the NC REST API this slow in general or is it just this specific endpoint or app?

**Comment by paulijar** [comment] 2017-12-01 21:55
@Biont As you mentioned yourself, you had lots of comments or questions. I now try to comment on them one-by-one. This reply got quite lengthy, but hey, you asked for it :D.

Your observation is correct and we are caching the collection.json containing the whole music library along with the cover images to the database. This wouldn't be done if there wasn't a significant performance benefit. As an example, I'm running Nextcloud on RaspberryPi 3 and my music collection contains 178 albums, most of which have embedded cover images. On this setup, reloading the Music app on Chrome now takes ~5 seconds and after this all the cover images are immediately visible. Size of the collection.json is 2.39 MB and it is loaded in ~1 second on my home LAN. Prior the server-side caching, loading the app took more than 10 seconds and then it took another 40 seconds before the last cover image became visible.

As I see it, there's nothing fundamentally wrong in storing large objects in the database. After all, the SQL CLOB and BLOB data types are designed to store up to 4 GB of data. However, if some database systems set packet size limit as low as 1 MB by default, then this might be considered a pragmatic reason to try to get rid of this caching design.

It should be noted that the total amount of cover image data embedded into collection.json has been limited to 3 MB. After reaching this limit, the rest of the covers are loaded using the "old way". Hence, the size of the collection should never get totally out of control due to the cover images. On the other hand, the size of the collection may be ~10 MB even without the covers if there are ~50k tracks.

It probably would be possible to use temporary files within the user space instead of the database to cache the collection.json. The benefit of the database is that it guarantees data integrity on all use cases, including e.g. simultaneous updates. Using temp files, this should be carefully handled in the application code.

According to my observations, calling any ownCloud/Nextcloud API endpoint always takes at least 300 ms, so the slowness is not specific for the Music app. I assume that the overhead is caused by the stateless nature of REST and PHP: on each call, the ownCloud/Nextcloud framework and the app in question has to be loaded from scratch. I guess that this constant overhead might be smaller on more powerful server hardware. 

The cover image caching on Firefox used to work so that the browser showed the cached images immediately and then reloaded the image from the server on the background and updated the shown image in case it would have got altered after the caching. I guess this was some automatic Firefox-magic and Chrome does not have a similar feature. Using the cache headers is a bit different thing as then images are actually not loaded from the server and any changes are not reflected on the UI.

IMHO, if client-side caching of images would be used, it should be implemented in such a way that any changes on the images would still be reflected on the UI immediately. The cover images are probably changed seldomly, but when they are, the user expects to see the change. Maybe this could be achieved by including an MD5 hash of the image contents to the image URL. Then, the headers could set the caching time to forever (or, say, to 1 year), and still changing the cover image wouldn't go unnoticed.

I don't know, what the `DataDisplayResponse` is meant for and the ownCloud-API reference is not very helpful on this, either. I just had to replace `JSONResponse` with something which can take pre-serialized JSON content (instead of automatically converting the passed data to JSON) and this class seemed to do the trick :). Caching the collection.json on the client-side would definitely be an option, too, but the cache-busting would require some thought as you mentioned. Not immediately reflecting the track additions/removals on the UI is not an option.

**Comment by Biont** [comment] 2017-12-03 11:58
I understand that storing the collection.json is a complex issue. My initial thought on this was "this is structured data, so storing it as (large amounts of) text is simply misusing a relational DB system", especially because the result is used as a file. However, I understand that the other options of storing it each come with their own drawbacks.

I don't know if it's worth putting in the time to implement alternative storage backends if ultimately, it's the concept of a monolithic collection itself that needs to go, as you said yourself earlier. The app should not crash if the SQL insert fails, but you'll probably know best what solution to implement for this. Choosing a different storage option is one of them. Failing and telling users to check their MySQL config is another.

I really think we should implement browser caching where possible and I'm glad you agree. Is there a simple way to pass a "last modified" timestamp (or any kind of hash that reflects the same thing) to the browser so that the collection cache can be busted? 

Busting **both** covers *and* collection when either of them changes could turn out to be tricky, since the cover URL is part of the collection.json, so any URL parameters for the cover URLs could only be renewed when the browser fetches a new collection.

The cache parameter for the collection.json would have to be `md5( $collectionChangedTime . $coversChangedTime)`, with `$coversChangedTime` being re-set when **any** cover changes. Then it could work.

**Comment by paulijar** [comment] 2017-12-03 22:33
@Biont I managed to implement the client-side caching of cover images in commit bd5d25fc2. It seems to work well but I need to still do some more testing before I'm willing to make a new application release. You can find more details from the commit message. I believe that the client-side caching of the images is a good idea, no matter what we do with the rest of the ideas presented in this discussion. 

I also studied the use of the ICache interface (https://doc.owncloud.org/api/classes/OCP.ICache.html) to implement the server-side caching using files instead of the DB. At first, it seemed like it could be used as a drop-in replacement for our DB caching and actually I got it working to certain degree, but then I ran into a critical shortcoming: the ICache can access only the cache of the logged-in user. But we need to be able to modify the cache also when using the command line tools and e.g. in the hook launched when a file has been shared with a user.

If we would want to cache also the collection.json on the client side, I think it could be achieved by splitting the endpoint `/api/collection` into two:
1. First the client should call `POST /api/prepare_collection` which would assemble the collection.json if not already cached on the server-side and return the hash of the collection.
2. Then the client should call `GET /api/collection?hash={hash value}` which would return the previously assembled collection.json along with the cache headers.

As we are probably not able to ditch the DB caching in very near future, it would probably make sense to catch  any exceptions on inserting cache entries. These should be logged but they should not prevent the use of the application; the app would just run slower if caching the collection.json is not possible because of the DB settings.

**Comment by paulijar** [comment] 2018-07-22 09:50
@azmeuk Have you tested any of the recent Music app versions? I believe that the brand new v0.8.0 should be already quite usable even with 50k tracks, provided you are using Firefox version 57.0 or newer. On Chrome it is still almost frozen.

**Comment by azmeuk** [comment] 2018-07-23 08:54
I just tested again. This is way way better. The app is usable with a very large library.

I just observed the page continuously loads cover images. Maybe it would be better if it would just only loads the cover of the displayed album plus a few more?

**Comment by paulijar** [comment] 2018-07-24 19:12
@azmeuk 

> I just tested again. This is way way better. The app is usable with a very large library, but after a few times Firefox consumes a lot of CPU and the page slows.

Okay, thanks, good to know. 

> I observed the page continuously loads cover images. Maybe it would be better if it would just only loads the cover of the displayed album plus a few more, and restart to load when the scrollbar moves.

Yeah, maybe something like this could be tested. On the other hand, the current implementation should work so that all the pictures will eventually get cached on the browser. Then the pictures should appear instantly, unless you hit the browser 'Refresh' which forces the browser to refetch all the cached pictures.

Anyway, I think it's now time to close this long-standing issue. All the actual show-stopping bugs reported here have been fixed and most of the performance improvements brought up during the discussion have been implemented, as well. Of course we can always come up with new potential improvements but let's handle those within new issue reports.

**Closed by paulijar** 2018-07-24 19:12 UTC
Labels: Bug
