### ISSUE TITLE
Music 0.3.10 blank screen on Owncloud 9 when "asset-pipeline.enabled" is set to "true"

### ISSUE THREAD

**Issue by roru69** [owncloud/music#484] opened 2016-04-01 08:46 UTC
Music 0.3.10 blank screen on Owncloud 9 when "asset-pipeline.enabled" is set to "true" in Config.php

This setting is recommended bij Gallery+ 15 to speed up things. Everything works except Mucic 0.3.10 which shows a blank sceen when.

When the setting is removed, Music works as expected.

**Comment by MorrisJobke** [comment] 2016-04-01 08:50
Duplicate of https://github.com/owncloud/music/issues/434

**Closed by MorrisJobke** 2016-04-01 08:50 UTC
