### ISSUE TITLE
Podcast from Radio-France cannot be fetched

### ISSUE THREAD

**Issue by testcocoon** [owncloud/music#937] opened 2022-01-28 09:06 UTC
Podcasts from Radio-France are not correctly fetched. 

Here is one example for a problematic RSS: https://radiofrance-podcast.net/podcast09/rss_10076.xml

It is displayed as completely empty (Music version 1.5.0, owncloud) without any podcast to listen. But it contains some entries.

**Comment by paulijar** [comment] 2022-01-28 21:42
Thanks for the report. However, I can't reproduce the problem. With ownCloud 10.6, the channel is fetched and shows 47 episodes:
![image](https://user-images.githubusercontent.com/8565946/151625232-9c1aa105-c592-43b3-ac62-72399098fa8c.png)

Is it possible that there has been some temporary problem on the Radio-France? Or can you still reproduce the issue if you try to import it again? Can you find anything from owncloud.log after the attempted import?

**Comment by testcocoon** [comment] 2022-01-29 10:33
I had the version 10.5.0 as owncloud server. I try then to update to 10.9. The problem is always there: the cover image is displayed but the list of podcasts are empty. And when I look on the RSS I see some items.

Is there a way to produce a log?

**Comment by paulijar** [comment] 2022-01-29 11:17
You should find the `owncloud.log` file under the data folder of your ownCloud installation. Alternatively, you can view and/or download the log from the web UI from the Admin settings. The specific location and options available via the UI vary depending on the ownCloud version.

**Comment by testcocoon** [comment] 2022-01-29 13:40
I'm finding the following error:
`Jan 29 14:37:48 fricker ownCloud[25380]: [YfVDK13s2pcQO3TL3HMfAAAAAAc][127.0.0.1][sfri][index][POST][/owncloud/index.php/apps/music/api/podcasts/11/update] Exception: {"Exception":"OCP\\App
Framework\\Db\\MultipleObjectsReturnedException","Message":"Did not expect more than one result when executing: query \"SELECT * FROM `*PREFIX*music_podcast_episodes` WHERE `*PREFIX*music_p
odcast_episodes`.`user_id` = ? AND `guid_hash` = ?  \"; parameters Array\n(\n    [0] => sfri\n    [1] => 0e4cb08abfa5f026f1ab3297259378ad\n)\n; limit \"\"; offset \"\"","Code":0,"Trace":"#0
 \/var\/www\/owncloud\/lib\/public\/AppFramework\/Db\/Mapper.php(372): OCP\\AppFramework\\Db\\Mapper->findOneQuery()\n#1 \/var\/www\/owncloud\/apps\/music\/lib\/Db\/PodcastEpisodeMapper.php
(66): OCP\\AppFramework\\Db\\Mapper->findEntity()\n#2 \/var\/www\/owncloud\/apps\/music\/lib\/Db\/BaseMapper.php(297): OCA\\Music\\Db\\PodcastEpisodeMapper->findUniqueEntity()\n#3 \/var\/ww
w\/owncloud\/apps\/music\/lib\/BusinessLayer\/PodcastEpisodeBusinessLayer.php(68): OCA\\Music\\Db\\BaseMapper->updateOrInsert()\n#4 \/var\/www\/owncloud\/apps\/music\/lib\/Utility\/PodcastS
ervice.php(260): OCA\\Music\\BusinessLayer\\PodcastEpisodeBusinessLayer->addOrUpdate()\n#5 \/var\/www\/owncloud\/apps\/music\/lib\/Utility\/PodcastService.php(195): OCA\\Music\\Utility\\Pod
castService->updateEpisodesFromXml()\n#6 \/var\/www\/owncloud\/apps\/music\/lib\/Controller\/PodcastApiController.php(158): OCA\\Music\\Utility\\PodcastService->updateChannel()\n#7 \/var\/w
ww\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(170): OCA\\Music\\Controller\\PodcastApiController->updateChannel()\n#8 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http
\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#9 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(100): OC\\AppFramework\\Http\\Dispatcher->dispatc
h()\n#10 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main()\n#11 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(344)
: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke()\n#12 \/var\/www\/owncloud\/lib\/base.php(927): OC\\Route\\Router->match()\n#13 \/var\/www\/owncloud\/index.php(54): OC::handleReq
uest()\n#14 {main}","File":"\/var\/www\/owncloud\/lib\/public\/AppFramework\/Db\/Mapper.php","Line":299}`

Are you able to understand the issue with this?

**Comment by paulijar** [comment] 2022-01-30 14:07
Yes, this log actually is very helpful, and it pointed towards what probably is the root cause.

The thing is, every podcast channel from Radio-France seems to have the same first episode called "Retrouvez tous les épisodes sur l’appli Radio France". Furthermore, this episode has the same GUID on every channel. There is now a bug in the Music app on how it handles the case where multiple channels contain an episode with identical GUID. So if the use has only a single Channel from Radio-France, then everything should work fine. But adding another is when the problems start.

However, I still couldn't actually see the problem described in the opening post. What I saw was that the first episode of the previous channel from Radio-France got removed when another channel was subscribed. But if there was some way to get those two episodes with identical GUIDs inserted to the database, then it's clear that an exception like the one shown above would happen. So the exact steps to reproduce the reported error are still unknown but the root cause is probably known and should be easy to fix.

**Comment by testcocoon** [comment] 2022-01-30 14:23
I'm not really sure, but as far I know the GUID is sometime broken for some podcast provider. I'm not sure if we can rely on the GUID. I guess that they don't have an unique GUID for each unique episode...
I have added a dump of my mysql tables. Maybe you can see if the GUID have an issue.

Thanks for the investigation.
[oc_music.zip](https://github.com/owncloud/music/files/7966073/oc_music.zip)
.

**Comment by paulijar** [comment] 2022-01-30 17:06
I checked your dump, and indeed, you have 11 channels where there is an episode with the same GUID. I don't know how to reach such situation but it should no longer be a problem once I fix the bug in the Music app.

**Comment by testcocoon** [comment] 2022-01-30 18:07
Sounds Good!

**Comment by paulijar** [comment] 2022-02-01 20:30
The fix for this has now been released in Music v1.5.1. Please reopen in case you still see the problem with this version.

**Closed by paulijar** 2022-02-01 20:30 UTC
Labels: Bug
