### ISSUE TITLE
Blank Page in Music 0.3.4

### ISSUE THREAD

**Issue by GutsBlack** [owncloud/music#298] opened 2014-09-25 23:22 UTC
I Have a problem with my owncloud 7, i have a blank page in music.

**Server**
Owncloud 7.0.2 / Nginx / Debian / Music 0.3.4 (git clone)

**Browser**
Test in Chrome / Firefox / Epiphany same problem
Clear cache and cookie

**javascript console in chrome**
Uncaught Error: Cannot find module 'function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}'

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=Music&p1=Error

https://myserver/assets/mp3.js.map 404 (Not Found)

**Mysql**
In mysql i see my file in oc_music_tracks like

**Logs Nginx**
2014/09/26 01:07:18 [error] 12524#0: _9442 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: *._._._, server: myserver, request: "GET /assets/     mp3.js.map HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "myserver"

**Comment by paulijar** [comment] 2017-04-01 19:37
This is probably duplicate of #434 and hence already fixed: the javascript error shows that injection has failed for some minified code.

**Closed by paulijar** 2017-04-01 19:37 UTC
Labels: 1 - Triaging, Bug
