### ISSUE TITLE
Scan hangs at "Scanning music... 578 of 6196" on IE 11 and Edge

### ISSUE THREAD

**Issue by chris001** [owncloud/music#557] opened 2016-12-12 01:22 UTC
Music add-on says, "New music available. Click here to start the scan."
Clicked there.
Scan starts and immediately hangs forever at "Scanning music... 578 of 6196" on Internet Explorer 11 and Edge, and Firefox 51.0b6 browsers.  All browsers are newest current versions.

The source code for this page appears to be here:
https://github.com/owncloud/music/blob/master/templates/partials/overview.php

**Comment by paulijar** [comment] 2016-12-12 22:00
@chirs001: This sounds very similar to #538. Can you try either with the latest development version of the Music app or by making the work-around suggested in the comments of #538 on your own?

**Comment by chris001** [comment] 2016-12-13 00:07
@paulijar 
By changing the line at this position where it checks for too many comments in the audio file (already fixed in master):
https://github.com/owncloud/music/blob/master/3rdparty/getID3/getid3/module.audio.ogg.php#L585
from `break 2` to `break;`, the infinite hang bug is fixed.

**Comment by paulijar** [comment] 2016-12-13 16:01
Closed as duplicate of an already fixed issue.

**Closed by paulijar** 2016-12-13 16:01 UTC
