### ISSUE TITLE
Kann nur Maximal 1050 Songs in die App laden mehr wird nicht geladen

### ISSUE THREAD

**Issue by xXSandro1994Xx** [owncloud/music#861] opened 2021-05-17 11:09 UTC
Es steht zwar das er weiter lädt aber es passiert ab 1050 songs nicht mehr.

**Comment by paulijar** [comment] 2021-05-17 17:20
Could you write in English, my understanding of German is very limited. When this problem happens, can you find any more details from the logs? Either owncloud.log or nextcloud.log, depending on which cloud you use.

Also, whenever you report an issue, it's always a good idea to mention at least:
- version of ownCloud or Nextcloud
- version of the Music app
- PHP version

**Comment by RandomBloke85** [comment] 2021-05-18 18:24
He can only load 1050 songs into the app, not more. It says it continue to load more, but nothing happens after that.

**Comment by paulijar** [comment] 2021-06-27 11:09
With no further info, it's impossible to study this any closer. Hence, closing. It's also possible that this has got fixed with the new getID3 library version included in the freshly released Music v1.2.1. Feel free to reopen along with more details, if the problem is still present with the latest Music app version.

**Closed by paulijar** 2021-06-27 11:09 UTC
Labels: Needs info
