### ISSUE TITLE
error -1

### ISSUE THREAD

**Issue by lonestartexas** [owncloud/music#1144] opened 2024-04-27 15:42 UTC
Hello.
The app stops scanning the music after a few minutes, and I get the error -1. The music is on sftp.

**Comment by paulijar** [comment] 2024-04-27 15:48
Thanks for the report. Which version of Nextcloud or ownCloud are you using? Can you find anything from nextcloud.log or owncloud.log after the stopped scanning?

**Comment by lonestartexas** [comment] 2024-04-27 15:58
29

**Comment by lonestartexas** [comment] 2024-04-27 16:10
No, only error -1

**Comment by paulijar** [comment] 2024-04-27 16:14
If you temporarily enable the logging on the debug level (loglevel=0), and retry the scanning, then the log should show the path of the file being scanned just before something goes wrong. Could you check this, and then test, can you play or download the said file via the Files app?

**Comment by lonestartexas** [comment] 2024-04-27 16:32
The only thing is what it could be."Can't get app storage, app files_external, user not logged in", but I'm logged in

**Comment by paulijar** [comment] 2024-04-27 16:35
Can you browse your SFTP storage in the Files app and download some files?

**Comment by lonestartexas** [comment] 2024-04-27 16:42
Yes

**Comment by lonestartexas** [comment] 2024-04-27 16:52
[PHP] Error: Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.mp3.php#1731
	POST /index.php/apps/music/api/scan
	from 192.168.50.1 by lonestar at Apr 27, 2024, 12:51:12 PM

**Comment by paulijar** [comment] 2024-04-27 16:58
Okay, that's a good lead. But then it would still be valuable to find the scanned file where this happens. So that we could see if the file has something unusual triggering the problem. Or is it the SFTP storage which is the important factor here.

Did I understood correctly that the app scanned some files without issues before hitting the problem? And does the problem now reoccur immediately when you start the scanning?

**Comment by lonestartexas** [comment] 2024-04-27 17:05
The app scanned some files, then stopped. Sometimes more files or less. I installed "music" two days ago, and it never scanned the whole folders.

**Comment by paulijar** [comment] 2024-04-27 17:09
So every time you reload the Music page, you can start a new scan? And it always scans some more files until it breaks?

**Comment by lonestartexas** [comment] 2024-04-27 17:14
No, I need to reset it, and then the app scans again.

**Comment by paulijar** [comment] 2024-04-27 17:23
So that sounds like it would always break on the same file. But if the number of files scanned varies, then it sounds like it wouldn't be always the same file. So that's a bit controversial. Did you try setting the loglevel to 0? With that, you should get lots of logging, most of which is irrelevant, but there could be something interesting in last lines before the "error -1".

**Comment by lonestartexas** [comment] 2024-04-27 17:23
![Screenshot_20240427_132241_Brave](https://github.com/owncloud/music/assets/56798813/0a03dbd8-d176-4a73-941e-30fb7b206334)
I need to click on it from time to time that the app keeps scanning

**Comment by paulijar** [comment] 2024-04-27 17:30
It might be possible also from the web UI, but the easiest way is probably to add `'loglevel => 0,` to the file `config/config.php`.
![image](https://github.com/owncloud/music/assets/8565946/d2daa198-56ed-4bb4-b6c3-8e4f6fee6cb2)

**Comment by lonestartexas** [comment] 2024-04-27 17:36
[music] Debug: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.
	GET /index.php/apps/logreader/api/poll?lastReqId=5D1RY08WvrGMaPdqDNIj
	from 192.168.50.1 by lonestar at Apr 27, 2024, 1:36:37 PM

**Comment by paulijar** [comment] 2024-04-27 17:38
That one is a knows issue and not related.

**Comment by lonestartexas** [comment] 2024-04-27 17:40
{"reqId":"zSvU8vpmRXFJ8OaFdqUT","level":0,"time":"2024-04-27T17:39:14+00:00","remoteAddr":"191.96.206.26","user":"lonestar","app":"workflowengine","method":"PROPFIND","url":"/remote.php/dav/files/lonestar/","message":"Flow activation: rules were requested for operation Block access to a file","userAgent":"Mozilla/5.0 (Linux) mirall/3.13.0git (Nextcloud, arch-6.8.6-arch1-1-surface ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.5.1","data":{"app":"workflowengine","level":"0"},"id":"662d384875143"}

**Comment by lonestartexas** [comment] 2024-04-27 17:41
There is no other message related to the music app

**Comment by paulijar** [comment] 2024-04-27 18:17
```
{"reqId":"zSvU8vpmRXFJ8OaFdqUT","level":0,"time":"2024-04-27T17:39:14+00:00","remoteAddr":"191.96.206.26","user":"lonestar","app":"workflowengine","method":"PROPFIND","url":"/remote.php/dav/files/lonestar/","message":"Flow activation: rules were requested for operation Block access to a file","userAgent":"Mozilla/5.0 (Linux) mirall/3.13.0git (Nextcloud, arch-6.8.6-arch1-1-surface ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.5.1","data":{"app":"workflowengine","level":"0"},"id":"662d384875143"}
```
Probably not related, either, since that's for `"app":"workflowengine"`. 

> There is no other message related to the music app

Okay, I was actually a bit mistaken because the debug log shows something about the scanned file *after* it has been scanned and not *before*. And even there, there's no file name shown. To see the file names/paths *before* the scanning is attempted, the scanning must be done from the command line. The following command would probably work for you from the root of Nextcloud:
`sudo -u www-data php ./occ music:scan lonestar`

**Comment by lonestartexas** [comment] 2024-04-27 23:34
After the command "sudo -u www-data php ./occ music:scan" I was able to scan in the app. Thank you for your help. Thank you.

**Comment by paulijar** [comment] 2024-04-28 14:43
Okay, great thing if it works. But that's still quite unexpected. I'd say that there's probably now some problem in the connection between Nextcloud and your SFTP storage which is not directly related to the Music app. But why the `occ music:scan` fixed this (temporarily ?), I have no idea.

**Comment by paulijar** [comment] 2024-05-27 19:28
Although the actual root cause of this behavior has not been identified, I'm pretty confident that the problem is not in the scope of the Music app. Hence, closing.

**Closed by paulijar** 2024-05-27 19:28 UTC
