### ISSUE TITLE
 sharing single audio files via public link

### ISSUE THREAD

**Issue by R7JANV1** [owncloud/music#944] opened 2022-02-08 22:08 UTC
When sharing single audio files via public link, Music Player is not used, unlike when sharing whole folders containing audio files.

![grafik](https://user-images.githubusercontent.com/90777102/153083556-a01cf982-78a5-4752-98d3-2e21f0e8a0a7.png)

**Comment by paulijar** [comment] 2022-02-09 19:06
Yes, this is intentional. There is already one player provided by Nextcloud, and I see no point in adding another. Sure, the Music app player could show the track title and artist name from the metadata but I don't see this as a big-enough boon to add the player.

On the other hand, ownCloud server doesn't provide a player for the individually shared files and there we do show the Music app player also in this case.

**Comment by paulijar** [comment] 2022-02-16 20:17
Works as intended => closing

**Closed by paulijar** 2022-02-16 20:17 UTC
