### ISSUE TITLE
(my)SQL error caused by utility/helper.php

### ISSUE THREAD

**Issue by rotdrop** [owncloud/music#361] opened 2015-04-06 11:04 UTC
The latest commit 9771cc0954163fd7216fe43a26a2381d39be2420 for utility/helper.php causes SQL errors
    
    An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 Table 'oc_music_albums' is specified twice, both as a target for 'UPDATE' and as a separate source for data

Also, the SQL in the sub-select somehow looks a little bit wrong: it selects `cover_file_id` from a join-table where the join is on `file_id` and `cover_file_id` with a where-clause `file_id == NULL`. Effectively, this means that also `cover_file_id` is already NULL.

Best,

Claus

**Comment by rotdrop** [comment] 2015-04-06 15:58
Sorry, too complicated. Also, my email is clear enough.

**Comment by MorrisJobke** [comment] 2015-04-07 07:06
@rotdrop Sorry ... this is just a dump bot. Everything is fine.

@butonic Can you have a look at your query?

**Comment by butonic** [comment] 2015-04-21 13:36
closing as duplicate of #358

**Closed by butonic** 2015-04-21 13:36 UTC
Labels: Bug
