### ISSUE TITLE
Any way to change sort order?

### ISSUE THREAD

**Issue by smartroad** [owncloud/music#477] opened 2016-03-13 11:01 UTC
Is there anyway to change the sort order? I would just like the list to display albums. At the moment all I have is a massive list sorted by artist/album/album year

One of my 'Albums' has about 100 tracks by different artists and years so my list is very large and unwieldy. I have been looking for a settings 'cog' but can't seem to find one :disappointed: I guess it is hardcoded at the moment or I am blind and can't see it!

**Comment by MorrisJobke** [comment] 2016-03-14 11:27
cc @owncloud/designers for some idea about this use case

**Comment by paulijar** [comment] 2017-04-23 17:38
Closing as duplicate of #429

**Closed by paulijar** 2017-04-23 17:38 UTC
Labels: Enhancement
