### ISSUE TITLE
Broken link in app icon on fresh install OC 9.0

### ISSUE THREAD

**Issue by Geo719** [owncloud/music#486] opened 2016-04-05 19:58 UTC
There is no link given in the href. The app icon does not work.

**Comment by benediktg** [comment] 2016-04-10 19:50
I can confirm the issue. This is an extract of the HTML code I get displayed by the browser:
```
<li data-id="music">
    <a href="" tabindex="3">
        <img class="app-icon svg" alt="" src="/apps/music/img/music.svg">
        <div class="icon-loading-dark" style="display:none;"></div>
        <span>Music</span>
    </a>
</li>
```
Note that the `href` attribute is empty.

**Comment by MorrisJobke** [comment] 2016-04-11 07:39
> Edit2: interesting, some time later it worked…

Mmmh ... I also can't reproduce anymore :(

**Comment by MorrisJobke** [comment] 2016-04-11 07:39
Let's close this and continue in #478

**Closed by MorrisJobke** 2016-04-11 07:39 UTC
Labels: Bug
