### ISSUE TITLE
Music app throws error code 500 in the browser

### ISSUE THREAD

**Issue by gerroon** [owncloud/music#381] opened 2015-05-25 02:08 UTC
This is what I get in the log

{"reqId":"f5e8eb2d9851a25d9e5c422bfb9a8c41","remoteAddr":"192.168.2.106","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\/md5\\/md5.min serverroot:\\/var\\/www\\/owncloud8\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud8\\/lib\\/private\\/templatelayout.php(156): OC\\Template\\ResourceLocator->find(Array)\n#1 \\/var\\/www\\/owncloud8\\/lib\\/private\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\n#2 \\/var\\/www\\/owncloud8\\/lib\\/private\\/template.php(118): OC_TemplateLayout->__construct('user', 'music')\n#3 \\/var\\/www\\/owncloud8\\/apps\\/music\\/appframework\\/http\\/templateresponse.php(124): OC_Template->fetchPage()\n#4 \\/var\\/www\\/owncloud8\\/apps\\/music\\/appframework\\/http\\/dispatcher.php(85): OCA\\Music\\AppFramework\\Http\\TemplateResponse->render()\n#5 \\/var\\/www\\/owncloud8\\/apps\\/music\\/appframework\\/app.php(54): OCA\\Music\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\PageController), 'index')\n#6 \\/var\\/www\\/owncloud8\\/apps\\/music\\/appinfo\\/routes.php(37): OCA\\Music\\AppFramework\\App::main('PageController', 'index', Array, Object(OCA\\Music\\DependencyInjection\\DIContainer))\n#7 [internal function]: OC\\Route\\Router->OCA\\Music\\{closure}(Array)\n#8 \\/var\\/www\\/owncloud8\\/lib\\/private\\/route\\/router.php(250): call_user_func(Object(Closure), Array)\n#9 \\/var\\/www\\/owncloud8\\/lib\\/base.php(782): OC\\Route\\Router->match('\\/apps\\/music\\/')\n#10 \\/var\\/www\\/owncloud8\\/index.php(36): OC::handleRequest()\n#11 {main}\",\"File\":\"\\/var\\/www\\/owncloud8\\/lib\\/private\\/template\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-05-25T02:06:57+00:00"}
{"reqId":"f5e8eb2d9851a25d9e5c422bfb9a8c41","remoteAddr":"192.168.2.106","app":"PHP","message":"js file not found: script:js\/md5\/md5.min serverroot:\/var\/www\/owncloud8 at \/var\/www\/owncloud8\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-05-25T02:06:57+00:00"}

using 8.0.3

**Comment by RealRancor** [comment] 2015-05-26 11:54
Hi,

very likely that you're running an outdated version of the music app not compatible with OC8:

https://github.com/owncloud/music/issues/377 , https://github.com/owncloud/music/issues/327

**Comment by paulijar** [comment] 2016-11-20 16:25
Closing as duplicate of the above mentioned issues.

**Closed by paulijar** 2016-11-20 16:25 UTC
Labels: Needs info
