### ISSUE TITLE
App glitches out when a new audio file is selected from the recent files tab in dashboard

### ISSUE THREAD

**Issue by Stan805** [owncloud/music#1126] opened 2024-02-04 07:29 UTC
When a recently uploaded audio file is uploaded and is selected from the recent files list, it will open it in a new tab and play it using the standard Nextcloud audio play UI, not the one the app provides for inside the files app. On top of that, if you exit the file without refreshing the page and try to play something in the same folder, it will play seemingly normal, until you back out of the folder you're currently in and go into it again. From there, the audio player will glitch out and either pause the song or go to the next one. The only way to fix the odd behavior is to refresh the page. This happens in Nextcloud 28.0.2.

**Comment by paulijar** [comment] 2024-02-04 11:53
Thanks for the report. By "recent files tab in dashboard", do you mean the "Recommended files" widget:
![image](https://github.com/owncloud/music/assets/8565946/e127b4e5-42d9-4e18-9b60-487877ba5eda)

If so, then I couldn't reproduce the problem with the steps above. For me, the audio file opened in the new tab using the embedded player provided by Music, and also navigating between the folders and playing other files didn't glitch as described above. The only glitch I saw was that after starting to play a file from the dashboard widget, and the navigating back and forth in the folders, the same file selected from the widget started to play again whenever I navigated to the folder where the file resides. But this is obviously a bug in the Nextcloud itself since the same happens also with image files.

**Comment by Stan805** [comment] 2024-02-06 00:13
Odd.. My thought process went to either having a conflicting app, or maybe its just .wav files, since that is how I had my music stored. I tried disabling every app besides Dashboard, Recommendations, and Music, but that didn't seem to fix it. But I also tried uploading a .flac file to see if it was the wav theory, but it didn't fix it either. I'm very confused to why this only happens to me. Are you running Nextcloud 28.0.2? Maybe the glitch is unique to my setup perhaps. I run Nextcloud in a Debian VM.

**Comment by paulijar** [comment] 2024-02-06 16:47
I was testing this on NC 28.0.2, too. But I now noticed that I can reproduce the problem using Chrome but not with Firefox. I guess that somehow the timings and order of execution of asynchronous functions ends up being different depending on the browser.

**Comment by paulijar** [comment] 2024-04-21 20:29
This is now fixed in Music v1.11.0.

**Closed by paulijar** 2024-04-21 20:29 UTC
Labels: Bug, 6 - Ready for release
