### ISSUE TITLE
Upgrade to Music v.1.3.1 breaks Subsonic Soundwaves Player - Nextcloud v.21.0.4

### ISSUE THREAD

**Issue by atkinsom** [owncloud/music#885] opened 2021-08-31 01:10 UTC
Hi,

I just upgraded to Music v.1.3.1 on Nextcloud v.21.0.4 and when I try to use my Soundwaves Subsonic player on my iPhone to select songs I get the following error "Server Error - There was a problem with your request: Required parameter 'musicFolderId' missing"

The test within the app confirms that I can connect successfully but when I try to tap to select songs I get the error above. I've included an attachment to assist with any troubleshooting. Thanks again for a great app.
![IMG_0973](https://user-images.githubusercontent.com/75316046/131425172-ffee5124-f711-4b0e-a2f9-95d87e08ed5c.PNG)

**Comment by paulijar** [comment] 2021-08-31 17:55
Thanks for the report. It seems that I have accidentally marked an argument as required when it ought to be optional. The fix requires just one `?` character if you wish to monkey patch your installation while waiting for the fix release. See the commit linked above for details.

**Comment by atkinsom** [comment] 2021-08-31 20:38
Thank you very much. Your suggestion worked like a charm. Cheers

**Comment by jecogeo** [comment] 2021-09-02 19:15
Just to let you all know, I'm having the same issue. However, I'm streaming via subsonic to a different client and the error is also different. I'm using play:Sub (iOS) and the message is "Token-based auth not supported". I use TOTP authentication on my NC instance and I'm streaming with no problem for months. Now I updated the app to 1.3.1 I'm facing this. Should I open another issue?

**Comment by paulijar** [comment] 2021-09-02 19:23
@jecogeo Your issue is duplicate of https://github.com/owncloud/music/issues/886, see that issue for the description and the solution.

**Comment by jecogeo** [comment] 2021-09-02 19:28
> @jecogeo Your issue is actually separate and already reported once in #886, see that issue for the description and the solution.

You're right! Thanks a lot!

**Comment by paulijar** [comment] 2021-09-05 16:59
The fix for this issue is now released in Music v1.3.2

**Closed by paulijar** 2021-09-05 16:59 UTC
Labels: Bug
