### ISSUE TITLE
can I stream music via shared link?

### ISSUE THREAD

**Issue by kiyoon** [owncloud/music#433] opened 2015-09-28 16:41 UTC
I want to share what I listen or watch to my friends. Fortunately, I can share link of video and it supports streaming video for a link access too.

I want to stream music also, so I installed Music plugin but it did not solve the problem. They only can download the music but not stream and listen instantly.

I found that when I share the directory, it is able to stream music. But when I share just ONE music file, then it is impossible to stream. Sometimes I want to share just one music, not the entire directory.

How can I make my music streamable to all my friends who got the shared link?
I mean, shared link of only "one" music file.

Thank you.

**Comment by rolandixor** [comment] 2016-05-22 01:59
If I share a folder I still get this issue.

**Comment by paulijar** [comment] 2017-08-02 20:12
This seems to be a duplicate of the issue #256.

**Comment by paulijar** [comment] 2017-09-04 20:26
This issue is fixed in the brand new release v0.5.0.

**Closed by paulijar** 2017-09-04 20:26 UTC
