### ISSUE TITLE
Ampache API JSON support

### ISSUE THREAD

**Issue by memen45** [owncloud/music#768] opened 2020-06-11 14:07 UTC
Currently it seems that only the XML part of the [Ampache API](https://github.com/ampache/ampache/wiki/Ampache-API) is implemented at "/ampache/server/xml.server.php". I think the JSON version is exactly the same, except for the return format. 

Is it possible to support JSON response format according to Ampache API specification at "/server/json.server.php"?

**Comment by paulijar** [comment] 2020-06-11 18:44
Yes, it would be possible, but it would require non-trivial amount of effort. On Subsonic, we can support both XML and JSON without much extra effort, because there is a 1-to-1 mapping between these two formats: One kind of XML structure is *always* converted to the same kind of JSON structure, regardless of the method in question.

On Ampache, on the other hand, there seems to be some subtle differences between the data provided via XML and JSON APIs. This means, that we cannot just make one conversion method, which would translate XML to JSON, because the correct translation differs according the method and property in question. I guess, that some of these differences might actually be unintended, and I'm not certain if the problem is in the actual Ampache implementation or only in the documentation.

Do you know of some client application which would use the JSON API? It would make much more sense to sink the development hours on this feature if someone was actually using this API.

**Comment by memen45** [comment] 2020-06-12 01:18
Haha yes, me! I have made an app to sync music from Subsonic servers to a Garmin watch. However, the watch has a size limit on the http responses, so playlists larger than ~25 songs exceed the limit. 

The Ampache API supports limit and offset parameters and would thus allow for large playlists to be synced properly as well sending multiple requests. Therefore I want to move to / extend support for Ampache API. On the watch, JSON responses can be easily parsed and used, while XML requests cannot.

I do not know about the implementation of other apps, but since the JSON is part of the Ampache API and generally more common to use than XML, I would expect there are more.

Agreed that it is indeed weird if the content of the responses differ between both formats. I was just wondering whether this JSON support is something on the (near future) roadmap or not.

**Comment by paulijar** [comment] 2020-06-12 21:14
Okay, maybe I could try to create some kind of "mostly compliant" Ampache JSON implementation for the next release. Or the one after that if it turns out to be more difficult task than I think. If we ignore the few oddities in the JSON API specification for now, then it *should* be quite straight forward task. With a quick look, I found one or two details form the spec where JSON API was asymmetric with the XML API. But there may well be others, and knowing for sure would require careful investigation.

**Comment by paulijar** [comment] 2020-06-15 19:57
@memen45 The first version of the Ampache JSON API support was just pushed to master. If you are anxious to give it a try, then go ahead and pull/download the latest Music app version form github.

The implementation doesn't even try to comply with the specification, instead it is basically a direct conversion from the XML API. On the other hand, I was told by the Ampache developers that the JSON API specification is not yet stable, so there are probably changes coming. I think that trying to comply with the spec is not worth the effort as long as the API is not considered stable. And I keep fingers crossed that some of the coming API specification changes are towards the current implementation in the Music app.

But anyway, no matter if you start to implement your client against the JSON API specification or the current implementation of the Music app, you most likely need to change it later.

**Comment by memen45** [comment] 2020-06-18 16:59
Great to see you already implemented it in such a short time, thanks a lot. I started testing (manually) against the XML version and use that to code the JSON implementation. I do not have time/resources to set up a dev nextcloud server and clone the latest changes, but anyways, I will only release the app when the support is officially included in the latest app version on Nextcloud.

In case I encounter unexpected responses or behavior, I will report back here or at the Ampache git.

**Comment by memen45** [comment] 2020-07-01 22:07
Do you know when it will be released to production version? I am looking forward to test it, since I have completed the draft implementation for the SubMusic app.

**Comment by paulijar** [comment] 2020-07-02 19:00
I can't say any exact date yet, but most likely it will be during July. I have a few ideas for improvements which I would like to implement during the summer. But maybe I'll try to squeeze out one release already by the end of the next week and then another one at late July or mid-August. I don't promise anything, though.

**Comment by paulijar** [comment] 2020-07-10 10:35
The initial Ampache JSON API support is now released in the Music app v0.15.0. I did some changes after my first implementation to comply better with the API specification (or what I believe to be its intention). Still, there is a good chance that some details need to be changed in the future versions.

**Comment by memen45** [comment] 2020-07-10 12:27
Thanks for the update! However, I get an internal server error when trying to do the handshake. XML version works fine, but the JSON version gives the following error (instead of returning session object):

> 
> [index] Error: Exception: Argument 1 passed to OCA\Music\Utility\Util::convertArrayKeys() must be of the type array, integer given, called in /var/www/html/nextcloud/apps/music/controller/ampachecontroller.php on line 717 at <<closure>>
> 
> 0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 125
>    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Music\Controller\AmpacheController {}, "jsonApi")
> 1. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
>    OC\AppFramework\App::main("AmpacheController", "jsonApi", OC\AppFramework\ ... {}, {_route: "music.ampache.jsonApi"})
> 2. <<closure>>
>    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "music.ampache.jsonApi"})
> 3. /var/www/html/nextcloud/lib/private/Route/Router.php line 299
>    call_user_func(OC\AppFramework\ ... {}, {_route: "music.ampache.jsonApi"})
> 4. /var/www/html/nextcloud/lib/base.php line 1008
>    OC\Route\Router->match("/apps/music/amp ... p")
> 5. /var/www/html/nextcloud/index.php line 38
>    OC::handleRequest()
> 
> GET /apps/music/ampache/server/json.server.php?action=handshake&timestamp=<>&auth=<>&user=<>

Should I open a new issue for this?

**Comment by paulijar** [comment] 2020-07-10 19:54
Okay, thanks for the info. I didn't actually test the handshake on JSON, as I had a session already opened by an XML client and I then hijacked the session to do JSON testing. Let's reopen this issue to get this solved.

**Comment by paulijar** [comment] 2020-07-10 22:09
@memen45 I think I got this fixed now. Could you try to monkey-patch your installation with the change shown above? The change is just rewriting one function of  ~10 lines of code and adding another function with 2 lines of code. I kind of dislike the idea of pushing a hotfix for all users just because of this, as very few of them would actually benefit from this fix.

**Comment by memen45** [comment] 2020-07-11 13:50
The handshake seems to work now with the last fix! I will further test some other endpoints as well and let you know when everything works as expected (I have to change some code, since the API changed slightly).

I was wondering the following: if I use the 'limit' and 'offset' parameters and it seems like the API returns the last page always if the offset exceeds the total available items. The last page can be detected by checking (response.size() < limit), however, sometimes there might be exactly 'limit' number of items on the last page. In that case I have to request again with increased 'offset', but then I receive the same last page. Should the API return an empty list if the offset exceeds the total number of items? Or do you have another suggestion on how to detect the end of the list?

**Comment by memen45** [comment] 2020-07-11 14:26
Last issue I am running into is that the 'stream' action is not supported. I think this one could have the exact same implementation as the Subsonic API, so I think it would be an easy fix. Other than that and the question above, everything works nicely!

**Comment by paulijar** [comment] 2020-07-11 18:39
> The handshake seems to work now with the last fix!

Great!

> if I use the 'limit' and 'offset' parameters and it seems like the API returns the last item always if the offset exceeds the total available items

This really shouldn't be the case. Which action were you testing with? I now tested `songs` and `artists`, but I couldn't reproduce this issue. For example, I had 162 artists in the collection, having indices 0...161. Setting the offset to 162 and limit to 10 returned me an empty result array. The same happened with offset 163, 164, or 1000.

**Comment by memen45** [comment] 2020-07-11 18:47
Tested with action=playlists and assumed all would work the same :sweat_smile:. Just tested playlist_songs and that one works correctly, so only for action=playlists the last item will show always. I think this is maybe since this is the "All tracks" playlist, which is auto generated.

**Comment by paulijar** [comment] 2020-07-11 19:04
Yes, you are right, that's an oversight with the "All tracks" list. I'll fix that.

**Comment by memen45** [comment] 2020-07-11 19:29
Great! The only issue remaining then is the implementation of action=stream. Would it be feasible to implement this (just like Subsonic without transcoding) or is there a reason it is not implemented?

**Comment by paulijar** [comment] 2020-07-11 20:36
The reason that the `stream` action has not been implemented so far is that it has been introduced only in the latest API version 400001. Meanwhile, the Music app is implementing the API version 350001. On some actions, we may support some arguments, though, which have been added by API version later than 350001. It's hard to tell, really, because the detailed content of each API version is not well documented.

The way the API version 350001 is intended to be used is that when you have a `song` entity, you look its property `url`, and then download or stream from that URL. If you look at the URLs we are returning here, you can see that we have actually implemented them using a proprietary argument `action=_play`. For this action, the song ID is given using the argument `filter` instead of `id` which should be used on the `stream` action.

But okay, it doesn't hurt to substitute the `_play` action with the new `download` action from 400001, and the add a dummy implementation for `stream` which is just the same as the the `download`. I'll do this shortly.

**Comment by memen45** [comment] 2020-07-12 09:10
Ah, that explains it. The documentation of the Ampache API is indeed lacking in versioning. Maybe they should have the specification in their git instead of in the wiki, so changes are visible and versions can be released. 
Anyways, I just tested the current version from the master branch and everything is working as expected now 🎉 .
Thanks a lot for your efforts!

**Comment by paulijar** [comment] 2020-07-12 19:46
There was another issue which made me hurry to release a new version 0.15.1. All the fixes discussed on this issue are included there, too.

@memen45 Feel free to link your application to our wiki at https://github.com/owncloud/music/wiki/Ampache if you think that it works well together with the Music app.

**Closed by paulijar** 2020-07-12 19:46 UTC
Labels: Enhancement

**Comment by memen45** [comment] 2020-07-12 22:24
Yes, the app works well with both the Subsonic and the Ampache endpoints of your app, so it would be nice if it was listed in your wiki as well (the app landing page is [SubMusic](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794)). I have updated the README on my git to link to your nextcloud app landing page as well, to make sure users install the correct one!

**Comment by paulijar** [comment] 2020-07-13 11:30
Okay, I linked SubMusic on the Music app wiki pages.
