### ISSUE TITLE
data too long for column 'name' at ...

### ISSUE THREAD

**Issue by panspektrum** [owncloud/music#716] opened 2019-09-15 09:09 UTC
while scanning with command line occ I get :

In AbstractMySQLDriver.php line 125:

"INSERT INTO `oc_music_artists`(`name`,`user_id` 
  ,`hash`) VALUES(?,?,?)' with params ["XXX yyyyyy, Associated Performer, Author, Compo 
  ser, Main Artist, Organ - xxx xxxxxx, Associated Performer, Main Artist, Violin - xxxx 
   xxxxxxx, Associated Performer, Main Artist, Violin - fffff ggggggg, Associated Perform 
  er, Main Artist, Viola - Clarice Jensen, Associated Performer, Cello, Main Artist - Br 
  ian Snow, Associated Performer, Cello, Main Artist - Mute Song", "<username>", "123456789012 
  12341234123412341234"]: "

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at  
   row 1

**Comment by paulijar** [comment] 2019-09-15 20:10
Thanks for the report. The problem seems to be caused by an overly long artist name in the metadata. The database schema sets the max length of artist, album, and track names to 256 characters.

The funny thing is, in my system the overly long names don't cause any problems. When I have tested this, the database management system has automatically truncated any overly long texts so that they fit the database table. But you are not the first one who reports this kind of issue. I haven't figured out, what is the significant difference between my setup and that of the reporter.

Anyway, I now added own truncation logic which is applied before adding the data to the database. This should fix the issue. If you wish, you can test it by downloading and manually installing the development version from github. Otherwise, you need to wait for the next release. It may still take some weeks before it is published.

**Comment by gagbo** [comment] 2019-10-10 19:31
Wouldn't it be better to leave the possibility to change the data fields to `text` instead of forcing the truncation ? I think I wouldn't mind the extra space taken for this

**Comment by paulijar** [comment] 2019-10-10 20:10
@gagbo Not necessarily. The extra space would be a non-issue, but using `TEXT` type might incur a performance hit on `SELECT` queries where such field is used as (part of) selection criteria.

**Comment by gagbo** [comment] 2019-10-11 12:17
Fair enough. And I forgot the real title will still be left untouched in the metadata of the files

**Comment by paulijar** [comment] 2019-10-12 22:49
The fix has now been released as part of the version 0.11.0.

**Closed by paulijar** 2019-10-12 22:49 UTC
