### ISSUE TITLE
Update error: Unable to generate a URL for the named route "music.page.index"

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#413] opened 2015-08-23 18:59 UTC
Sometimes when updating I get the following error message:
```
Symfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "music.page.index" as such route does not exist.
```

Any idea @MorrisJobke?

**Comment by LukasReschke** [comment] 2015-08-23 19:09
Probably dupe of https://github.com/owncloud/core/issues/18224

**Comment by MorrisJobke** [comment] 2015-08-24 06:44
Yep. Duplicate of a core issue.

**Closed by MorrisJobke** 2015-08-24 06:44 UTC
Labels: Bug
