### ISSUE TITLE
Display by folder

### ISSUE THREAD

**Issue by thiagoricciardi** [owncloud/music#651] opened 2018-06-19 20:52 UTC
Nice app, really enjoying it! I have a library of more than 32k music files in my library (> 120GB) and everything seems to be working great!

As it is a very good app, I have an improvement request:
It would be nice to have on the left panel an option to display music by folder.

Thanks a lot!

**Comment by nachoparker** [comment] 2018-08-27 02:05
Agreed, that would be fantastic. Ideally the list would be hierarchical, as many users use different folders to classify their collections.

**Comment by Bibo-Joshi** [comment] 2018-10-31 08:47
That would indeed be very useful! I'm looking forward to it :)

**Comment by Gatak** [comment] 2018-12-28 22:09
This would be very useful. Many Various Artists albums have different album tags for individual songs, for example what album the song originally came from. This makes the Album layout/view impossible to use to find my music. 

A folder based view solved this nicely :)

It would also be great if a folder view would be available in ampache. If that isn't possible perhaps it would be possible to generate virtual playlists based on folder names.

**Comment by Acreen** [comment] 2019-06-30 18:11
I'm wondering if this feature has been implemented yet? There has been a commit but Right now I am not able to filter by folder. I'm using version 0.9.5 in Nextcloud

**Comment by paulijar** [comment] 2019-06-30 19:02
Yes, a very simple folders view was implemented in the commit shown above. However, there was a bug in the implementation which was blocking the releasing. This bug was fixed with commit 4bd5b8923 a week ago. Now I believe that the feature is ready for releasing. So when the next release rolls  out, the feature will be included. I don't know yet when I'll make the release but it should happen during July.

**Comment by Acreen** [comment] 2019-06-30 19:25
Thanks for the info. I'm really looking forward to it since my artists in mp3s are messed up awfully. You are doing a great job!

**Comment by paulijar** [comment] 2019-07-22 22:04
The version 0.10.0 including the Folders view is now published.

The view is nothing fancy, just a flat list of folders containing audio files in alphabetical order. It should work regardless if the folders are normal local folders or shared by another user or mounted from an external storage. However, the performance is significantly better for the normal local folders. In case the user has hundreds or thousands of shared/mounted folders, it may take some time to open the view. And it the extreme case, opening the view will fail on timeout.

**Closed** 2019-07-23 10:43 UTC
Labels: Enhancement

**Comment by Acreen** [comment] 2019-07-27 19:50
Thx mate, you are awesome!

**Comment by FadeFx** [comment] 2019-07-28 15:28
Hi Paul,
I have to report that folder view made chrome on android freze and crash, on firefox it is working as intended as it seems.

However, a flat folder view is not very helpfull, as it just resembles the albums view for most of us i guess. If music is sorted like ../genre/artist/album/tracks.mp3 or /genre/album/tracks.mp3 it would be helpfull if we could have a nested folder view.

**Comment by paulijar** [comment] 2019-07-28 18:23
@FadeFx 
>I have to report that folder view made chrome on android freze and crash, on firefox it is working as intended as it seems.

Thanks for the info. How many files and folders do you have in your music collection? I was able to open the Folders view on Chrome for Android even on my "large test" account which has ~60k tracks in 9347 folders. It was insanely slow, though, beyond all usability. But I saw no freezes or crashes. Also Firefox for Android was unusably slow on this account, and Chrome for Windows was on the verge of being unusable. So as of today, Firefox on PC is the only viable alternative when the user has tens of thousands of tracks.

> However, a flat folder view is not very helpfull

Yes, I can see how nested structure could be useful in many cases. However, creating it would take quite a bit of additional effort. But almost everything implemented so far could be utilized also in such a view.

Maybe the biggest obstacle is that I can't quite figure out, what the view should look like. Ideally, the view should be
1. usable on desktop PC, portrait mobile screen, and everything in between
2. scalable to any number of folder nesting levels
3. consistent with the other views

But fulfilling all these requirements simultaneously seems tricky. In the Albums view, we have two levels of nesting which are separated with different title font sizes. This scheme does not scale well to unlimited number of nesting levels.

**Comment by FadeFx** [comment] 2019-07-29 05:32
I have maybe 3000 tracks in prox 200 folders, so not that big. However mu nextcloud instance runs on a raspberry pi 2, probably that plays in there as well.

On folders i see what your problem is, for my part i would prefere expanding/collapsing folders, so only one is visible at a time, for now i have settled to normal files app to play my music, as it nearly does what i want it to do.

**Comment by paulijar** [comment] 2019-10-12 23:14
The people hoping for a hierarchical folders view and/or folders support for Ampache might be interested to know that the newly released version 0.11.0 of the Music app includes support for the Subsonic API. There, we support also browsing by folders in hierarchical manner. This was possible and rather simple, because the Subsonic API and the available clients have been designed for hierarchical navigation from day one.

**Comment by nachoparker** [comment] 2019-10-13 02:31
@paulijar many thanks for this progress. Can we hope for hierarchical folder browsing in the web interface at some point in the future?

That's how many of us organize our music.

Great job again!

**Comment by FadeFx** [comment] 2019-10-13 05:28
@paulijar subsonic sounds super cool, as ampache seems to be far less supported. 

@nachoparker for me browsing in files and playing there seems to be nearly fully sufficient, only thing thats not as i wish is that it stops at the end of the folder instead of going to the next folder, but that is also the case with many music player apps on android.

**Comment by paulijar** [comment] 2019-10-13 10:31
@nachoparker I wouldn't say "never" but currently I have no plans to start working on the hierarchical folders view on the web UI. If I end up implementing that, I would probably aim for an indented tree-like structure where all the folder levels could be shown simultaneously. I feel that view style with only one folder visible at a time would be too different from the UX of the other views. And as @FadeFx implied, the Files app already provides this kind of view, and I wouldn't want to duplicate that to the Music app.

**Comment by FadeFx** [comment] 2019-10-13 11:50
@paulijar only thing i would love to see would be something like a continious play option, so if one folder is played to the end it should go up one level, into the next folder and play that one... this would make it perfect imo

**Comment by nachoparker** [comment] 2019-10-13 22:32
@paulijar yes, that is more or less what I was envisioning too. Also it is true that we have something that kind of works already using Files, but we cannot have it jump to the next folder or add it to a playlist from there.

Anyhow, grateful for your current work. I know how this goes since I also run my open source project. Things don't come for free... everything requires a lot of work. Very grateful again for your work.

> And as @FadeFx implied

Actually I also said this in my comment :P
