### ISSUE TITLE
v1.6.0 on Nextcloud 25 RC 3 does not work at all - no settings, no Covers

### ISSUE THREAD

**Issue by frake65** [owncloud/music#1017] opened 2022-10-12 18:23 UTC
Is there any chance to have Music working on the upcoming Nextcloud version?
At this time I do not get any covers and settings is also not functional at all on Firefox 105.0.3.
Anything to help on for the community?
Thanks and best regards

**Comment by paulijar** [comment] 2022-10-12 18:46
It used to work on 25beta1, but something probably changed since. I yesterday downloaded NC25rc3 but it doesn't seem to work at all for me. Maybe something went wrong on the installation... I'm afraid I might not have much time to investigate this during the next week or two.

**Comment by androidphrases** [comment] 2022-10-13 11:29
Hey folks, I was just about to raise this. For me it half works - there seems to be both a display issue, where you have to drag the browser window in to make the albums appear, and also some kind of a connection issue where the alphabet shortcuts don't take you to the relevant part of the library any more.
Thanks for a superb app!

**Comment by paulijar** [comment] 2022-10-15 16:40
Okay, now I managed to successfully install NC25 rc5 and could reproduce the issue. The app seems to be unusable in full screen window on PC but if the window or screen is narrow enough to collapse the navigation pane on the left, then the app can be used almost normally. The alphabet navigation doesn't work, though.

This has to be fixed, of course, but I'm afraid I might not have time for that during the next week or so.

**Comment by paulijar** [comment] 2022-10-31 22:27
The compatibility with NC25 is now fixed in the freshly released Music v1.7.0.

**Closed by paulijar** 2022-10-31 22:27 UTC
