### ISSUE TITLE
Rhythmbox error

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/music#467] opened 2016-02-09 01:51 UTC
I get this error when connecting to ownCloud Music 0.3.8 from Rhythmbox 3.1:

```
Songs response: g-io-error-quark: HTTP Error: Internal Server Error (0)
```

Not sure if it's a bug with one or the other.

**Comment by qirtaiba** [comment] 2016-02-10 18:51
The Apache log shows this:

    192.168.42.113 - - [09/Feb/2016:19:31:04 -0800] "GET /owncloud/index.php/apps/music/ampache/server/xml.server.php?action=handshake&auth=***removed***&timestamp=1455075058&user=terminus&version=350001 HTTP/1.1" 200 460 "-" "gvfs/1.22.2"
    192.168.42.113 - - [09/Feb/2016:19:31:04 -0800] "GET /owncloud/index.php/apps/music/ampache/server/xml.server.php?action=playlists&auth=***removed*** HTTP/1.1" 200 102 "-" "gvfs/1.22.2"
    192.168.42.113 - - [09/Feb/2016:19:31:05 -0800] "GET /owncloud/index.php/apps/music/ampache/server/xml.server.php?action=songs&auth=***removed***&offset=0&limit=5000 HTTP/1.1" 500 9705 "-" "gvfs/1.22.2"

**Comment by bts-1979** [comment] 2016-05-24 16:33
Have you found any solution? I'm getting a similar error when attempting to play music on oc9 through Tomahawk on OSX

**Comment by paulijar** [comment] 2017-09-11 18:04
The Apache log line
```
192.168.42.113 - - [09/Feb/2016:19:31:05 -0800] "GET /owncloud/index.php/apps/music/ampache/server/xml.server.php?action=songs&auth=***removed***&offset=0&limit=5000 HTTP/1.1" 500 9705 "-" "gvfs/1.22.2"
```
tells us that something has failed when the Music app was handling the Ampache endpoint `songs`. That's all we can know with the provided data. The owncloud.log file could have had more details.

**Comment by paulijar** [comment] 2017-11-13 20:01
@qirtaiba @bts-1979 Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by qirtaiba** [comment] 2017-11-29 06:28
No, but instead Rhythmbox seems to get stuck on "Updating songs" (or at least, it is taking a long time) I see this on the console:

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/ampache/AmpacheBrowser.py", line 542, in handshake_cb
    handshake['update'][0:18],
KeyError: 'update'

**Comment by greku** [comment] 2018-02-03 21:45
For your information, I have Rhythmbox 3.4 on my computer. I installed the ampache_plugin from  https://github.com/lotan/rhythmbox-ampache and latest music app.
Seems to work fine.

**Comment by paulijar** [comment] 2018-05-21 18:18
Since the original error reported on this issue seems to be fixed, I'm closing the issue. On the new problem mentioned on comment from Nov-29-2017, there has been at least some problem in extracting metadata from APE tag when trying to get a cover image for a file. This might be completely unrelated to the Ampache API. Anyway, a new issue should be opened for this if the problem is still present on the newest Music app version.

**Closed by paulijar** 2018-05-21 18:18 UTC
