### ISSUE TITLE
russian names in file names

### ISSUE THREAD

**Issue by DimmoK** [owncloud/music#785] opened 2020-09-16 07:27 UTC
Hello!
Sorry for  my bad English.

I have a problem: russian name is not reading - Òàíöåâàëüíûé ðàé 7 "Ðóññêèé" (example).

How to change encoding or install correct encoding?

Thanks!

**Comment by paulijar** [comment] 2020-09-16 18:33
It's likely that your files have ID3v1 tags with non-standard encoding. ID3v1 only officially supports ISO-8859-1 ("Latin 1") encoding, but it is not uncommon to find files containing Windows-1251 -encoded Cyrillic characters in the ID3v1 tags. Historically, this was the only choice for the Russian speaking world but for the past 20 years, the right solution has been to use ID3v2 which supports the Unicode character set.

If you can share one such file with me, I can take a look if there would be anything we could do to improve the compatibility. You can find my email address in my profile. Be aware, though, that I'm quite busy with other things for the next 2 weeks. Hence, it will probably take some time before I can actually investigate the issue.

**Comment by paulijar** [comment] 2020-12-02 19:46
Cannot study this further without a sample file. Closing.

**Closed by paulijar** 2020-12-02 19:46 UTC

**Comment by theheyon** [comment] 2021-04-24 21:32
Hey on there!

I can give some [sample](https://github.com/owncloud/music/files/6370729/uz-sample.zip) )
This happens not to all of files. Something with encoding of tags here, for sure.

**Comment by paulijar** [comment] 2021-04-25 14:39
@theheyon Thanks for the sample. This file has clearly incorrect ID3v2 tags, and in fact, I couldn't find a single application which would show the proper Cyrillic metadata for it. I tested foobar2000, MP3 Diags, VLC, Windows 10 file details, and Groove Music.

The problem is that the ID3v2 tags themselves claim to be using ISO-8859-1 encoding, but you still need to interpret them using Windows-1251 encoding to see the proper metadata. Also the ID3v1 tags in the file use Windows-1251 encoding (which is non-standard), but this is a moot point as the Music app will anyway prioritize using the ID3v2 tags when those are available.

**Comment by theheyon** [comment] 2021-04-25 17:51
Thanks a lot for filling a gap in understanding some principles of mp3 format itself!

I hope it will help someone too.
