### ISSUE TITLE
Playing music delays and has during the waiting time a very high cpu load

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#605] opened 2017-12-28 09:57 UTC
You open music but displaying the album delays heavily. CPU load is low.
When clicking on a track, **right after** opening music when the albums are displayed, playing delays for many minutes (you think it is dead) and CPU load is very high during this time!

![image](https://user-images.githubusercontent.com/3321281/34407104-fdbf7b3a-ebbc-11e7-8afe-24cc5235cae9.png)

**Comment by paulijar** [comment] 2017-12-30 12:25
I assume that this is because some browsers (Chrome, at least) want to load all the album cover images before the playback can start. Firefox, on the other hand, can start playing the music while images are still being loaded.

In case of large music library,  loading all the cover images may take quite much time. At least on my low-power server, fetching a single cover (or any other PHP query) always takes at least ~300 ms. Now, if there are 1000 albums with a cover image, that would already add up to 5 minutes! In addition, if the cover images are large, then the server has to also downscale them which may take ~1 s per image. In case you were talking about high CPU load on the server-side, it could be caused by the downscaling.

However, this should be a problem only on the first times the Music app is loaded. The server stores the downscaled images, so this work has to be done only once. In addition, the images are eventually cached on the client-side, making them appear instantly when the Music app is opened. For a technical reason, the images cannot be cached on the client when the application is opened for the first time, but on the second opening they get cached and on third and latter times the images should come from the client-side cache. Of course, if you clear the browser cache, then the images are loaded from the server again.

**Comment by paulijar** [comment] 2022-11-13 21:25
This problem has probably got solved already by Music v0.12.0 released in the end of 2019. After that, we have not loaded all the album covers when application loaded but only upon scrolling down the albums list.

**Closed by paulijar** 2022-11-13 21:25 UTC
